import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','content-type':'application/json'};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:cors});
type Color='red'|'green'|'yellow'|'blue';
type Piece={id:string;steps:number};
type Player={id:string;displayName:string;cruiseId?:string|null;color:Color;pieces:Piece[];ready:boolean};
type State={matchId:string;roomId:string;players:Player[];currentPlayerIndex:number;dice:number|null;phase:'await_roll'|'await_move';status:'lobby'|'playing'|'finished';winnerId?:string};
const colors:Color[]=['red','green','yellow','blue'];const offsets=[0,13,26,39];const safe=new Set([0,8,13,21,26,34,39,47]);const BASE=-1;const FINISHED=58;
const id=()=>crypto.randomUUID();
async function user(req:Request){const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)throw Error('Authentication required');const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw Error('Invalid session');return data.user}
async function profile(uid:string){const {data}=await admin.from('profiles').select('display_name,big_cruise_id').eq('id',uid).maybeSingle();return data||{display_name:'Cruiser',big_cruise_id:null}}
function publicState(s:State){return {...s,players:s.players.map(p=>({...p,pieces:p.pieces.map(piece=>({...piece}))}))}}
function fresh(matchId:string,roomId:string,players:Player[]):State{return{matchId,roomId,players:players.map(p=>({...p,pieces:Array.from({length:4},(_,i)=>({id:`${p.id}-${i}-${id()}`,steps:BASE}))})),currentPlayerIndex:0,dice:null,phase:'await_roll',status:'playing'}}
function current(s:State){return s.players[s.currentPlayerIndex]}
function abs(index:number,steps:number){return steps<0||steps>=52?null:(offsets[index]+steps)%52}
function can(piece:Piece,dice:number,index:number){return piece.steps!==FINISHED&&(piece.steps===BASE?dice===6:piece.steps+dice<=FINISHED)}
function legal(s:State,uid:string){if(s.status!=='playing'||s.phase!=='await_move'||s.dice===null||current(s).id!==uid)return[];const index=s.players.findIndex(p=>p.id===uid);return s.players[index].pieces.filter(p=>can(p,s.dice!,index)).map(p=>p.id)}
function next(s:State){s.currentPlayerIndex=(s.currentPlayerIndex+1)%s.players.length;s.dice=null;s.phase='await_roll'}
function capture(s:State,index:number,steps:number){const pos=abs(index,steps);if(pos===null||safe.has(pos))return;for(let i=0;i<s.players.length;i++){if(i===index)continue;for(const piece of s.players[i].pieces)if(abs(i,piece.steps)===pos)piece.steps=BASE}}
async function session(roomId:string){const {data:room,error:re}=await admin.from('game_rooms').select('*').eq('code',roomId).single();if(re||!room)throw Error('Room not found');const {data:players,error:pe}=await admin.from('game_players').select('user_id,display_name,cruise_id,ready').eq('room_code',roomId).order('joined_at');if(pe)throw pe;const {data:sess,error:se}=await admin.from('game_sessions').select('id,state,version,status').eq('room_code',roomId).order('started_at',{ascending:false}).limit(1).single();if(se||!sess)throw Error('Match session not found');return{room,players:players||[],sess}}
async function recordResult(s:State){if(!s.winnerId)return;const {data:sessionRow}=await admin.from('game_sessions').select('id,room_code').eq('id',s.matchId).single();if(!sessionRow)return;for(const p of s.players){const won=p.id===s.winnerId;await admin.from('game_results').insert({session_id:s.matchId,user_id:p.id,game:'ludo',result:won?'win':'loss',hosted:false});await admin.from('game_matches').insert({user_id:p.id,game:'ludo',result:won?'win':'sit',hosted:false,room_code:sessionRow.room_code});await admin.from('game_stats').upsert({user_id:p.id,game:'ludo',played:1,won:won?1:0,last_played:new Date().toISOString()},{onConflict:'user_id,game'});await admin.from('profiles').update({games_played:1,wins:won?1:0,updated_at:new Date().toISOString()}).eq('id',p.id)}}
Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response('',{headers:cors});const u=await user(req);const b=await req.json().catch(()=>({}));const action=String(b.action||'');
if(action==='create'){const pr=await profile(u.id);const code=Math.random().toString(36).slice(2,6).toUpperCase();const room=await admin.from('game_rooms').insert({code,game:'ludo',host_user_id:u.id,host_name:pr.display_name,kind:'private',status:'open',seats:4,filled:1}).select().single();if(room.error)throw room.error;const player=await admin.from('game_players').insert({room_code:code,user_id:u.id,display_name:pr.display_name,cruise_id:pr.big_cruise_id,is_host:true,ready:true});if(player.error)throw player.error;const sess=await admin.from('game_sessions').insert({room_code:code,game:'ludo',host_user_id:u.id,status:'open',state:null,version:0}).select('id').single();if(sess.error)throw sess.error;return json({code,matchId:sess.data.id,status:'lobby'})}
if(action==='join'){const code=String(b.code||'').toUpperCase();const {data:room,error}=await admin.from('game_rooms').select('*').eq('code',code).single();if(error||!room)throw Error('Room not found');if(room.status!=='open')throw Error('Match already started');const pr=await profile(u.id);const ins=await admin.from('game_players').upsert({room_code:code,user_id:u.id,display_name:pr.display_name,cruise_id:pr.big_cruise_id,is_host:false,ready:false},{onConflict:'room_code,user_id'});if(ins.error)throw ins.error;await admin.from('game_rooms').update({filled:(await admin.from('game_players').select('user_id',{count:'exact',head:true}).eq('room_code',code)).count||1,updated_at:new Date().toISOString()}).eq('code',code);return json({code,status:'lobby'})}
const code=String(b.code||'').toUpperCase();const loaded=await session(code);if(!loaded.players.some(p=>p.user_id===u.id))throw Error('You are not in this room');let s:State=loaded.sess.state||{matchId:loaded.sess.id,roomId:code,players:loaded.players.map((p,i)=>({id:p.user_id,displayName:p.display_name,cruiseId:p.cruise_id,color:colors[i],pieces:[],ready:p.ready})),currentPlayerIndex:0,dice:null,phase:'await_roll',status:'lobby'};s.players=s.players.map(p=>{const row=loaded.players.find(x=>x.user_id===p.id);return {...p,ready:row?.ready??p.ready}});
if(action==='state')return json(publicState(s));
if(action==='ready'){const q=await admin.from('game_players').update({ready:Boolean(b.ready)}).eq('room_code',code).eq('user_id',u.id);if(q.error)throw q.error;return json(publicState(s))}
if(action==='start'){if(s.status!=='lobby')throw Error('Match already started');if(loaded.players.length<2)throw Error('Need at least 2 players');if(!s.players.every(p=>p.ready))throw Error('Everyone must be ready');s=fresh(loaded.sess.id,code,s.players);await admin.from('game_sessions').update({status:'live',state:s,version:loaded.sess.version+1}).eq('id',loaded.sess.id).eq('version',loaded.sess.version);await admin.from('game_rooms').update({status:'live',updated_at:new Date().toISOString()}).eq('code',code);return json(publicState(s))}
if(action==='roll'){if(current(s).id!==u.id||s.phase!=='await_roll'||s.status!=='playing')throw Error('Not ready to roll');s.dice=Math.floor(Math.random()*6)+1;s.phase='await_move';if(!legal(s,u.id).length)next(s)}
if(action==='move'){if(current(s).id!==u.id||s.phase!=='await_move'||s.dice===null)throw Error('Not ready to move');const index=s.players.findIndex(p=>p.id===u.id),piece=s.players[index].pieces.find(p=>p.id===b.pieceId);if(!piece||!can(piece,s.dice,index))throw Error('Illegal move');const rolled=s.dice;piece.steps=piece.steps===BASE?0:piece.steps+rolled;capture(s,index,piece.steps);if(s.players[index].pieces.every(p=>p.steps===FINISHED)){s.status='finished';s.winnerId=u.id;s.dice=null;s.phase='await_roll'}else if(rolled===6){s.dice=null;s.phase='await_roll'}else next(s)}
if(action==='leave'){await admin.from('game_players').delete().eq('room_code',code).eq('user_id',u.id);return json({left:true})}
if(action==='rematch'){if(s.status!=='finished')throw Error('Finish the match first');s=fresh(loaded.sess.id,code,s.players);}
if(['roll','move','rematch'].includes(action)){const update=await admin.from('game_sessions').update({state:s,status:s.status==='finished'?'ended':'live',version:loaded.sess.version+1,ended_at:s.status==='finished'?new Date().toISOString():null}).eq('id',loaded.sess.id).eq('version',loaded.sess.version).select().maybeSingle();if(update.error||!update.data)throw Error('Game changed; refresh and try again');if(s.status==='finished')await recordResult(s)}return json(publicState(s));
}catch(e){return json({error:e instanceof Error?e.message:'Unexpected error'},400)}});
