export type DayId = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type Subtheme = {
  n: string;
  name: string;
  concept: string;
  description: string;
  mood: string;
  palette: string;
  merch: string;
  social: string;
  activity: string;
};

export type Day = {
  id: DayId;
  n: string;
  weekday: string;
  subBrand: string;
  line: string;
  spice: number;
  spiceNote: string;
  photo: string;
  photoAlt: string;
  accent: string;
  accent2: string;
  paper: string;
  ink: string;
  token: string;
  token2: string;
  motif: string;
  mood: string[];
  programs: string[];
  palette: { name: string; hex: string; role: string }[];
  voice: string;
  merchHero: string;
  subthemes: Subtheme[];
};

export const days: Day[] = [
  {
    id: "mon",
    n: "01",
    weekday: "Monday",
    subBrand: "Dominion State",
    line: "Power is quiet. Power is earned.",
    spice: 7,
    spiceNote: "Classy, dominant",
    photo: "/brand/days/mon.jpg",
    photoAlt: "Nigerian man in a black heavyweight tee, Lagos alley, burgundy night light.",
    accent: "#7A1F33",
    accent2: "#C48A5A",
    paper: "#0B0B0B",
    ink: "#F3EFE4",
    token: "dom",
    token2: "dom-warm",
    motif: "Three vertical weight bars. Quiet skyline. No crown.",
    mood: ["Masculine", "Sophisticated", "Confident", "Dominant", "Aspirational", "Mature"],
    programs: ["MCM Gifting", "The Men's Club", "Prime Time"],
    palette: [
      { name: "Midnight", hex: "#0B0B0B", role: "Field" },
      { name: "Dominion Burgundy", hex: "#7A1F33", role: "Accent" },
      { name: "Warm Restraint", hex: "#C48A5A", role: "Secondary — aged, not gold" },
      { name: "Bone", hex: "#F3EFE4", role: "Type" },
    ],
    voice: "Short. Earned. No hype. A man who already did the work.",
    merchHero: "Back print: the lion and the king. Chest spark burgundy. DOMINION STATE in Barlow.",
    subthemes: [
      {
        n: "1.1",
        name: "Dominion State",
        concept: "Quiet authority as a place.",
        description: "The master of the day. A room of men who do not announce themselves. Black field, one burgundy slash, 〽️ as the only medal.",
        mood: "Still, heavy, editorial.",
        palette: "Midnight + burgundy. Warm restraint at 5%.",
        merch: "Heavyweight tee. Stacked STATE on the back. Chest 〽️ in burgundy.",
        social: "One portrait. One line. No collage.",
        activity: "Prime Time check-in. Who moved this week without posting it.",
      },
      {
        n: "1.2",
        name: "The Men's Code",
        concept: "Brotherhood as protocol.",
        description: "Seven unwritten rules of the room, numbered 01–07. Not a manifesto poster. A code you keep in the neck of a shirt.",
        mood: "Precise, numbered, private.",
        palette: "Burgundy numerals on Bone or reversed on Midnight.",
        merch: "Inner-neck print of the seven lines. Outer is clean.",
        social: "One rule a week. Number big. Copy small.",
        activity: "Drop your code. The room votes the one that is actually lived.",
      },
      {
        n: "1.3",
        name: "Silent Winners",
        concept: "Results without the speech.",
        description: "Almost-empty composition. One mark. The win is implied. This is the anti-flex.",
        mood: "Negative space, confidence.",
        palette: "Black-on-black. Burgundy only on the 〽️.",
        merch: "Tonal black-on-black hoodie. 〽️ embroidered, no contrast thread except burgundy.",
        social: "Before/after with no caption flex. Let the room clock it.",
        activity: "Silent Winners thread — post the win, no speech.",
      },
      {
        n: "1.4",
        name: "Built Different",
        concept: "Character as architecture.",
        description: "Load-bearing type. Blueprint grid. Weight, not swagger. Construction of a man, not a gym advert.",
        mood: "Structural, measured.",
        palette: "Bone type, burgundy grid, midnight field.",
        merch: "Oversized tee. Condensed LOAD type as a beam across the back.",
        social: "Grid overlay on a night portrait. One measurement: consistency.",
        activity: "Built Different hour — what are you constructing this month.",
      },
      {
        n: "1.5",
        name: "Legacy Mode",
        concept: "What you leave, not what you wear.",
        description: "Inheritance without luxury-porn. Roman numerals, names, the ones coming behind you.",
        mood: "Warm restraint, long time.",
        palette: "Warm restraint type on midnight. Burgundy rule.",
        merch: "Long sleeve. MODE VII at the cuff. No chest logo.",
        social: "A name. A lesson. A date.",
        activity: "Legacy notes — write one thing you want the younger ones to keep.",
      },
      {
        n: "1.6",
        name: "Prime Time",
        concept: "21:00. Peak hours of the man.",
        description: "The Men's Club hour. Clock as graphic. Not a Rolex. A time.",
        mood: "Punctual, nocturnal, sharp.",
        palette: "Burgundy 21:00 on black.",
        merch: "Cap. 21:00 in Bone. Small 〽️ on the side.",
        social: "Countdown to Prime Time Space.",
        activity: "Prime Time Space. Gifting. The Men's Club.",
      },
      {
        n: "1.7",
        name: "The Stand",
        concept: "When one of us moves, the room stands.",
        description: "Brotherhood as posture. Not a throne. A line of men who show up.",
        mood: "Loyal, upright, together.",
        palette: "Seven small 〽️ in a row. Burgundy.",
        merch: "Tote. THE STAND on one face. 〽️ on the other.",
        social: "Stand-up posts for a member who needs the room.",
        activity: "The Stand — public backing, jobs, gifting.",
      },
    ],
  },
  {
    id: "tue",
    n: "02",
    weekday: "Tuesday",
    subBrand: "Too Lit To Stress",
    line: "No filter energy. Unapologetic.",
    spice: 10,
    spiceNote: "Flirty, loud, adult",
    photo: "/brand/days/tue.jpg",
    photoAlt: "Lagos club interior, hot pink and electric yellow light, adult nightlife.",
    accent: "#FF2B6B",
    accent2: "#FFF200",
    paper: "#0B0B0B",
    ink: "#F3EFE4",
    token: "lit",
    token2: "lit-yel",
    motif: "Double slash, −8°. Club strobe as geometry. Not a heart.",
    mood: ["Loud", "Flirty", "Playful", "Club", "Confident", "Adult", "High-energy"],
    programs: ["Flirt Day", "Shoot Your Shot", "Reality Check", "Hot Seat", "Smash or Pass"],
    palette: [
      { name: "Midnight", hex: "#0B0B0B", role: "Field" },
      { name: "Hot Pink", hex: "#FF2B6B", role: "Lead accent" },
      { name: "Electric Yellow", hex: "#FFF200", role: "Hit — not Danfo Yellow" },
      { name: "Bone", hex: "#F3EFE4", role: "Type" },
    ],
    voice: "Loud. Flirty. Adult. If it would get you muted in church, it belongs here.",
    merchHero: "Back print: the knot. TOO LIT stacked in Barlow. Chest spark hot pink.",
    subthemes: [
      {
        n: "2.1",
        name: "Too Lit To Stress",
        concept: "Unapologetic club energy as a uniform.",
        description: "Master of the day. Pink slash, electric yellow mark. Stress is for other rooms.",
        mood: "Strobe, offset type, heat.",
        palette: "Pink + electric yellow on midnight. Never Danfo Yellow here.",
        merch: "Oversized tee. TOO LIT stacked. Slash through the second line.",
        social: "Club still. One line. Pull up.",
        activity: "Flirt Day open thread. Keep it adult, keep it kind enough.",
      },
      {
        n: "2.2",
        name: "Flirt Frequency",
        concept: "The art of the opener.",
        description: "A fake station — 98.7 — for lines that actually land. Radio wave as graphic, not a heart.",
        mood: "Playful, tuned-in.",
        palette: "Electric yellow numerals, pink wave.",
        merch: "Long sleeve. 98.7 at the cuff. Pink 〽️ on chest.",
        social: "Drop your opener. The room rates it.",
        activity: "Flirt Frequency — best line of the night.",
      },
      {
        n: "2.3",
        name: "Shot Clock",
        concept: "Shoot your shot before time runs out.",
        description: "Courage as a sport. Target ring, not a weapon. The clock is the design.",
        mood: "Competitive, bright, urgent.",
        palette: "Pink ring, yellow numerals.",
        merch: "Shorts. Shot clock 04 at the hem.",
        social: "24-hour shot clock. Post the attempt.",
        activity: "Shoot Your Shot. The room is the court.",
      },
      {
        n: "2.4",
        name: "Hot Seat",
        concept: "One person. Public questions. Public heat.",
        description: "Spotlight circle. Chair as an abstract block. Confession with an audience.",
        mood: "Exposed, funny, adult.",
        palette: "Pink circle on black. Yellow questions.",
        merch: "Cap. Seat in pink. No mascot.",
        social: "Hot Seat graphic with tonight's name.",
        activity: "Hot Seat Space. Smash or Pass as a game, not cruelty.",
      },
      {
        n: "2.5",
        name: "Reality Check",
        concept: "The unfiltered mirror.",
        description: "Split composition. Performance vs the actual. Tuesday tells the truth after the flirt.",
        mood: "Sharp, honest, still loud.",
        palette: "Half pink, half yellow, type reversed.",
        merch: "Tote. CHECK on one side, 〽️ on the other.",
        social: "Two-panel post. The story vs the story.",
        activity: "Reality Check round. No speeches.",
      },
      {
        n: "2.6",
        name: "Attraction Index",
        concept: "Chemistry as playful data.",
        description: "Score bars that refuse to be a corporate dashboard. Heat as a meter.",
        mood: "Numeric, cheeky.",
        palette: "Pink bars, yellow 〽️ as the needle.",
        merch: "Sticker pack. Index marks 1–10.",
        social: "Tonight's index. Vote with replies.",
        activity: "Attraction Index poll — culture, not bodies as meat.",
      },
      {
        n: "2.7",
        name: "After Dark Confessions",
        concept: "Tuesday night honesty.",
        description: "The volume drops one notch. Pink becomes the curtain. Still adult. Still a cruise.",
        mood: "Lower light, still flirty.",
        palette: "Pink at 40%. Yellow as the only hit.",
        merch: "Hoodie. Confessional slash inside the hood.",
        social: "Confession prompt. No screenshots of other people.",
        activity: "After Dark Confessions thread. Close the night.",
      },
    ],
  },
  {
    id: "wed",
    n: "03",
    weekday: "Wednesday",
    subBrand: "Divine Energy",
    line: "She moves different.",
    spice: 6,
    spiceNote: "Empowering, sensual",
    photo: "/brand/days/wed.jpg",
    photoAlt: "Editorial portrait of a Nigerian woman, rose and nude lighting, Lagos night.",
    accent: "#C45A72",
    accent2: "#E6C8B4",
    paper: "#0B0B0B",
    ink: "#F3EFE4",
    token: "divine",
    token2: "nude",
    motif: "A single motion arc. Path, not a halo. Not a flower.",
    mood: ["Feminine", "Powerful", "Sensual", "Elegant", "Confident", "Empowering"],
    programs: ["WCW Gifting", "Ladies Circle", "Girl Talk", "Personal Growth"],
    palette: [
      { name: "Midnight", hex: "#0B0B0B", role: "Field" },
      { name: "Nude", hex: "#E6C8B4", role: "Paper / skin of the system" },
      { name: "Rose", hex: "#C45A72", role: "Accent" },
      { name: "Danfo Yellow", hex: "#F5C400", role: "5% house accent only" },
    ],
    voice: "Warm, precise, unhurried. She does not need to shout to own the room.",
    merchHero: "Back print: she moves different. DIVINE ENERGY in Barlow. Chest spark rose.",
    subthemes: [
      {
        n: "3.1",
        name: "Divine Energy",
        concept: "Force without the performance of force.",
        description: "Master of the day. Spiritual, not religious. Nude field, rose 〽️, one arc.",
        mood: "Elegant, grounded, lit from inside.",
        palette: "Nude + rose on midnight. Danfo only as a 5% pip.",
        merch: "Heavyweight tee. DIVINE in nude. Rose 〽️.",
        social: "One portrait. She looks at the camera. We look back.",
        activity: "WCW Gifting. Ladies Circle opens.",
      },
      {
        n: "3.2",
        name: "She Moves Different",
        concept: "Presence as choreography.",
        description: "Gait, timing, the way she enters a Space. Elongated type with a trail.",
        mood: "Motion, long lines.",
        palette: "Rose trail, nude type.",
        merch: "Oversized tee. MOVES as a stretched wordmark.",
        social: "A still that implies motion. No dance-challenge junk.",
        activity: "She Moves Different — drop a win that did not need a caption.",
      },
      {
        n: "3.3",
        name: "Soft Power",
        concept: "Quiet influence.",
        description: "A thin rose line on black. The opposite of Tuesday. Power that does not advertise.",
        mood: "Minimal, close, sure.",
        palette: "Rose line, Bone type, midnight.",
        merch: "Tonal black hoodie. One rose stitch line.",
        social: "One sentence. No thread.",
        activity: "Soft Power notes — who changed the room without taking the mic.",
      },
      {
        n: "3.4",
        name: "Main Character",
        concept: "Narrative ownership.",
        description: "Title card. Film-still crop. She is not a supporting role in anyone's plot.",
        mood: "Editorial, cinematic.",
        palette: "Nude title, rose underscore.",
        merch: "Cap. ERA in rose. 〽️ side.",
        social: "Title-card graphic over a portrait.",
        activity: "Main Character check-in. What chapter are you in.",
      },
      {
        n: "3.5",
        name: "Her Era",
        concept: "A timestamp of becoming.",
        description: "Year lockup. Not a trend cycle. A period she named herself.",
        mood: "Declarative, warm.",
        palette: "Nude year, rose 〽️.",
        merch: "Long sleeve. Year at the cuff.",
        social: "Her Era — name the era in three words.",
        activity: "Era declarations. The Circle holds them.",
      },
      {
        n: "3.6",
        name: "The Circle",
        concept: "Ladies Circle as geometry.",
        description: "Overlapping rings. Not a flower, not a sisterhood-cliché sun. A room.",
        mood: "Together, protected, open.",
        palette: "Three rose rings, nude fill at 10%.",
        merch: "Tote. Circle rings. 〽️ in the gap.",
        social: "Circle invite. Girl Talk prompt.",
        activity: "Ladies Circle Space. Girl Talk. Growth without lecture.",
      },
      {
        n: "3.7",
        name: "Unfinished Woman",
        concept: "Growth, not perfection.",
        description: "An incomplete stroke. She is not a finished file. Personal growth as a design idea.",
        mood: "Honest, becoming, unashamed.",
        palette: "Broken rose arc. Nude type.",
        merch: "Sticker. Incomplete 〽️.",
        social: "Unfinished — what are you still building.",
        activity: "Personal growth round. No guru voice.",
      },
    ],
  },
  {
    id: "thu",
    n: "04",
    weekday: "Thursday",
    subBrand: "Back When It Was Real",
    line: "Echo era. Rooted in reality.",
    spice: 5,
    spiceNote: "Nostalgic + adult confession energy",
    photo: "/brand/days/thu.jpg",
    photoAlt: "Nigerian living room at night, CRT glow, sepia, old family frames.",
    accent: "#C4A574",
    accent2: "#F2E6D0",
    paper: "#1A140E",
    ink: "#F2E6D0",
    token: "echo",
    token2: "cream",
    motif: "Halftone field + a date stamp. Film, not a filter pack.",
    mood: ["Nostalgic", "Emotional", "Warm", "Late-night", "Retro", "Reflective"],
    programs: ["Throwback Music", "Throwback Picture Games", "Confessions"],
    palette: [
      { name: "Echo Black", hex: "#1A140E", role: "Field" },
      { name: "Sepia", hex: "#C4A574", role: "Accent" },
      { name: "Cream", hex: "#F2E6D0", role: "Paper / type" },
      { name: "Midnight", hex: "#0B0B0B", role: "House anchor" },
    ],
    voice: "Slower. Remember when. Names, songs, the version of you before the algorithm.",
    merchHero: "Back print: the cassette. BACK WHEN IT WAS REAL in Barlow. Chest spark sepia.",
    subthemes: [
      {
        n: "4.1",
        name: "Back When It Was Real",
        concept: "Memory as the product.",
        description: "Master of the day. Sepia timestamp. The cruise before the rebrand, the city before the glass.",
        mood: "Warm, late, honest.",
        palette: "Cream type on echo black. Sepia stamp.",
        merch: "Heavyweight tee. ECHO ERA. Date stamp on the hem.",
        social: "One old photo, one line, no dump.",
        activity: "Throwback picture game. Confessions after.",
      },
      {
        n: "4.2",
        name: "Old School",
        concept: "Pre-algorithm culture.",
        description: "Cassette and radio as geometry — rectangles and a circle — not clip-art electronics.",
        mood: "Analog, sturdy.",
        palette: "Sepia blocks on cream reverse.",
        merch: "Cap. OLD in cream. 〽️ sepia.",
        social: "One song that raised you.",
        activity: "Throwback music hour.",
      },
      {
        n: "4.3",
        name: "Small Small",
        concept: "Childhood, Naija-scale.",
        description: "Exercise-book lines. Not a cartoon. The version of us that was still becoming.",
        mood: "Tender, lined, true.",
        palette: "Cream paper, sepia rules.",
        merch: "Tote. Lined field. Small 〽️.",
        social: "Childhood street / school / house. One image.",
        activity: "Small Small stories. Keep it kind.",
      },
      {
        n: "4.4",
        name: "Classic Frequency",
        concept: "The songs that still work.",
        description: "Vinyl groove as concentric rings. Track numbers. Not a streaming screenshot.",
        mood: "Musical, round, lasting.",
        palette: "Sepia rings, cream centre 〽️.",
        merch: "Long sleeve. Track 04 at the cuff.",
        social: "Classic Frequency playlist drop.",
        activity: "Throwback music. The room adds two songs each.",
      },
      {
        n: "4.5",
        name: "The Album",
        concept: "Old photos as a game.",
        description: "Polaroid proportion. Date in the white. Faces optional. The object is the frame.",
        mood: "Collected, handled, faded.",
        palette: "Cream frame, sepia image field.",
        merch: "Sticker. Fake polaroid with 〽️.",
        social: "Guess who / guess when. No bullying old photos.",
        activity: "The Album game.",
      },
      {
        n: "4.6",
        name: "First Loves",
        concept: "The ones that formed you.",
        description: "Letter paper. A name redacted. Adult confession, not teen drama.",
        mood: "Private, warm, late.",
        palette: "Cream paper, sepia type, one redacted bar.",
        merch: "Hoodie. Redacted line on the back.",
        social: "First Loves prompt. No exposing people.",
        activity: "Confession round. Soft.",
      },
      {
        n: "4.7",
        name: "Naija Nostalgia Net",
        concept: "2go, BBM, Nairaland, early Twitter.",
        description: "WAP-era geometry. Pixel-adjacent without becoming 8-bit novelty. The internet that made us.",
        mood: "Digital-old, specific, ours.",
        palette: "Sepia pixels on echo black.",
        merch: "Oversized tee. NET in cream, 〽️ as the cursor.",
        social: "What was your first handle.",
        activity: "Old internet stories. The room will lie and we will know.",
      },
    ],
  },
  {
    id: "fri",
    n: "05",
    weekday: "Friday",
    subBrand: "Play Your Vibe",
    line: "Fresh heat. The sound of the culture.",
    spice: 8,
    spiceNote: "Dance, flirt, vibe",
    photo: "/brand/days/fri.jpg",
    photoAlt: "Lagos dance floor, purple and cyan lights, Afrobeats energy.",
    accent: "#6A2C91",
    accent2: "#3DFFF2",
    paper: "#0D0A14",
    ink: "#F3EFE4",
    token: "play",
    token2: "play-cyan",
    motif: "Seven equalizer bars. Sound as architecture. Not a vinyl clip-art.",
    mood: ["Afrobeats", "Amapiano", "Club", "Discovery", "Dance", "Youth", "Energy"],
    programs: ["New Music", "BIG CRUISE Playlist", "Open Verse", "Artist Discussions", "Music Battles"],
    palette: [
      { name: "Night", hex: "#0D0A14", role: "Field" },
      { name: "Play Purple", hex: "#6A2C91", role: "Accent" },
      { name: "Cyan", hex: "#3DFFF2", role: "Hit" },
      { name: "Bone", hex: "#F3EFE4", role: "Type" },
    ],
    voice: "Energy. Track titles. Pull up. The caption should sound like a DJ talking to the floor.",
    merchHero: "Back print: the session. PLAY YOUR VIBE in Barlow. Chest spark cyan.",
    subthemes: [
      {
        n: "5.1",
        name: "Play Your Vibe",
        concept: "Playlist as identity.",
        description: "Master of the day. What you play is who you are tonight. Seven bars, one 〽️.",
        mood: "Loud enough, designed.",
        palette: "Purple field, cyan bars.",
        merch: "Oversized tee. PLAY stacked. Cyan 〽️.",
        social: "Playlist cover. No Spotify screenshot as the design.",
        activity: "Drop two songs. The room builds the night.",
      },
      {
        n: "5.2",
        name: "Fresh Heat",
        concept: "New music as weather.",
        description: "The Friday bag. Heat as rising bars. Discovery, not gatekeep.",
        mood: "Hot, new, generous.",
        palette: "Cyan rising, purple ground.",
        merch: "Cap. HEAT in cyan.",
        social: "Fresh Heat list. Five tracks. No essay.",
        activity: "New Music round. Artist discussion if it earns it.",
      },
      {
        n: "5.3",
        name: "Open Verse",
        concept: "The room has bars.",
        description: "Lined paper plus a waveform of seven bars. Community writing, not a talent show.",
        mood: "Written, rhythmic.",
        palette: "Bone lines, cyan pulse.",
        merch: "Long sleeve. Verse lines inside the cuff.",
        social: "Open Verse prompt. 8 bars.",
        activity: "Open Verse. Keep the roast for Sunday.",
      },
      {
        n: "5.4",
        name: "The Bag",
        concept: "The week's songs as an object.",
        description: "A tote/bag silhouette used as a type container. The bag is the playlist.",
        mood: "Carried, shared, full.",
        palette: "Purple bag, cyan type.",
        merch: "Tote. The actual bag. Bars on the side.",
        social: "What's in the bag this week.",
        activity: "Music bag drop. Community playlist.",
      },
      {
        n: "5.5",
        name: "Log Drum",
        concept: "Amapiano as graphic law.",
        description: "Log-drum hits as even bars. South African-Nigerian floor. Rhythm you can see.",
        mood: "Four-to-the-floor, night.",
        palette: "Even cyan bars, purple between.",
        merch: "Joggers. Bar graphic at the calf.",
        social: "Log Drum hour. One mix.",
        activity: "Amapiano hour in the Space.",
      },
      {
        n: "5.6",
        name: "Battle Deck",
        concept: "Music battles, designed.",
        description: "Split vs. Two tracks, one night. Not a shouting match — a deck.",
        mood: "Competitive, clean, loud.",
        palette: "Left purple, right cyan.",
        merch: "Sticker. VS with 〽️ as the hinge.",
        social: "Battle Deck graphic. Vote in replies.",
        activity: "Music battle. Winner announcement uses the same split.",
      },
      {
        n: "5.7",
        name: "After The Space",
        concept: "The afterparty of the playlist.",
        description: "When the Space ends and the songs keep going. Cyan on purple night. Come-down energy.",
        mood: "Late, glowing, together.",
        palette: "Cyan 〽️, purple wash.",
        merch: "Hoodie. AFTER on the back, small.",
        social: "After The Space recap. Tracklist.",
        activity: "Hang. No more games. Just the bag.",
      },
    ],
  },
  {
    id: "sat",
    n: "06",
    weekday: "Saturday",
    subBrand: "Read Between The Lines",
    line: "Unsent thoughts. Feel don't send.",
    spice: 11,
    spiceNote: "Adult only",
    photo: "/brand/days/sat.jpg",
    photoAlt: "Late-night Lagos apartment, deep red lamp, phone face-down, unsent note.",
    accent: "#9B1228",
    accent2: "#9A7B12",
    paper: "#0E0506",
    ink: "#F3EFE4",
    token: "line",
    token2: "dyel",
    motif: "Redaction bars. The design is what you don't show.",
    mood: ["Intimate", "Mysterious", "Emotional", "Late-night", "Confessional", "Adult"],
    programs: ["Secret Messages", "Anonymous", "Dating Games", "Dating Palava", "Delete Your Match", "Let's Talk Sex", "Naughty Hour"],
    palette: [
      { name: "Blood Night", hex: "#0E0506", role: "Field" },
      { name: "Deep Red", hex: "#9B1228", role: "Accent" },
      { name: "Dark Yellow", hex: "#9A7B12", role: "Secondary — not Danfo" },
      { name: "Bone", hex: "#F3EFE4", role: "Type that survives redaction" },
    ],
    voice: "Lower volume. Intimate. Between the lines. Adult without being a porn caption.",
    merchHero: "Back print: the unsent. READ BETWEEN THE LINES in Barlow. Chest spark deep red.",
    subthemes: [
      {
        n: "6.1",
        name: "Read Between The Lines",
        concept: "The unsaid as the brand.",
        description: "Master of the day. Redacted type. Desire as atmosphere. Adult, not graphic.",
        mood: "Close, dark, designed.",
        palette: "Deep red bars, bone fragments, dark yellow 〽️.",
        merch: "Heavyweight tee. A sentence half-barred. 〽️ ends it.",
        social: "One redacted line. The room fills it.",
        activity: "Secret Messages open. Anonymous drop.",
      },
      {
        n: "6.2",
        name: "Unsent",
        concept: "Feel don't send.",
        description: "Draft bubble. The message that stayed. The most honest paragraph in the phone.",
        mood: "Held, unsent, heavy.",
        palette: "Bone draft, red send-slash.",
        merch: "Long sleeve. UNSENT inside the cuff.",
        social: "Unsent prompt. No names.",
        activity: "Unsent hour. Write it. Don't post the person.",
      },
      {
        n: "6.3",
        name: "Anonymous Drop",
        concept: "The box is the product.",
        description: "Masked type. A slot. Community as a confessional that does not leak.",
        mood: "Sealed, adult, safe-enough.",
        palette: "Red box, bone type, 〽️ as the seal.",
        merch: "Tote. DROP. No other type.",
        social: "Anonymous Drop is open. Rules in the alt text.",
        activity: "Anonymous. Dating palava. No exposing.",
      },
      {
        n: "6.4",
        name: "Dating Palava",
        concept: "Relationship chaos as editorial.",
        description: "Torn ticket. The story is a mess; the layout is not. Adult dating, Nigerian edition.",
        mood: "Messy content, clean frame.",
        palette: "Torn red, dark yellow stub.",
        merch: "Sticker. PALAVA ticket.",
        social: "Palava of the week. Vote the wildest (kind).",
        activity: "Dating Palava. Delete Your Match as a game.",
      },
      {
        n: "6.5",
        name: "Delete Your Match",
        concept: "The after.",
        description: "Strike-through as the whole identity. What you walked away from.",
        mood: "Final, dry, adult.",
        palette: "Bone type, red strike, dark yellow 〽️.",
        merch: "Cap. A struck word. 〽️ remains.",
        social: "Delete Your Match stories. No revenge posting.",
        activity: "Delete Your Match round.",
      },
      {
        n: "6.6",
        name: "02:00",
        concept: "Late-night frequency.",
        description: "Naughty Hour without being graphic. The clock is the design. 02:00 is a place.",
        mood: "Nocturnal, low light, charged.",
        palette: "02:00 in bone, red field, dark yellow pip.",
        merch: "Hoodie. 02:00 on the back. Nothing on the chest.",
        social: "02:00 is live. Let's talk, adult.",
        activity: "Naughty Hour / Let's Talk Sex. Suggestive, not pornographic.",
      },
      {
        n: "6.7",
        name: "The Quiet Want",
        concept: "Desire as atmosphere.",
        description: "Close crop. No body-as-product. Heat in the crop, the blur, the red.",
        mood: "Sensual, editorial, unsaid.",
        palette: "Red wash, bone fragment, 〽️.",
        merch: "Oversized tee. WANT in a whisper size.",
        social: "A crop, a line, no more.",
        activity: "Quiet Want — attraction without the performance.",
      },
    ],
  },
  {
    id: "sun",
    n: "07",
    weekday: "Sunday",
    subBrand: "Chaos Culture",
    line: "No rules. No limits. Just chaos.",
    spice: 12,
    spiceNote: "Maximum chaos",
    photo: "/brand/days/sun.jpg",
    photoAlt: "Lagos street at dusk, crowd laughing, acid green and orange shop paint.",
    accent: "#C8F542",
    accent2: "#FF4D1A",
    paper: "#0A0C08",
    ink: "#F3EFE4",
    token: "chaos",
    token2: "wild",
    motif: "Offset stamp. Two plates that do not register. Collision as craft.",
    mood: ["Chaotic", "Competitive", "Funny", "Meme-heavy", "Loud", "Unexpected", "Playful"],
    programs: ["Wild N Out Games", "Dark Hour", "Roast Battles", "Meme Battles", "Community Challenges"],
    palette: [
      { name: "Chaos Black", hex: "#0A0C08", role: "Field" },
      { name: "Acid Green", hex: "#C8F542", role: "Lead" },
      { name: "Wild Orange", hex: "#FF4D1A", role: "Collision" },
      { name: "Midnight", hex: "#0B0B0B", role: "House anchor" },
    ],
    voice: "Chaotic, roast-first, still fam. All-caps sparingly. If it isn't funny, it isn't Sunday.",
    merchHero: "Back print: the blast. CHAOS CULTURE in Barlow. Chest spark acid.",
    subthemes: [
      {
        n: "7.1",
        name: "Chaos Culture",
        concept: "The house style for disorder.",
        description: "Master of the day. Two plates, bad register, perfect intent. Maximum spice, still designed.",
        mood: "Loud, colliding, ours.",
        palette: "Acid + orange on chaos black.",
        merch: "Oversized tee. CHAOS in acid, CULTURE in orange, offset.",
        social: "Sunday is open. No rules graphic.",
        activity: "Wild N Out games. The room is the stage.",
      },
      {
        n: "7.2",
        name: "No Rules",
        concept: "A stamp that voids the week.",
        description: "VOID / NO RULES as a rubber stamp. Bureaucracy used against itself.",
        mood: "Official-unofficial.",
        palette: "Orange stamp, acid 〽️.",
        merch: "Cap. Stamp on the crown.",
        social: "No Rules. The only rule is the roast stays in the family.",
        activity: "Anything-goes opener.",
      },
      {
        n: "7.3",
        name: "Roast Protocol",
        concept: "Formalized chaos.",
        description: "Numbered roast cards. The insult is wild; the layout is a system. Love underneath.",
        mood: "Card, numbered, lethal-kind.",
        palette: "Acid card, orange number.",
        merch: "Sticker pack. Roast cards 01–07.",
        social: "Roast Protocol is in session. Tag in.",
        activity: "Roast battles. Winner announcement uses the card.",
      },
      {
        n: "7.4",
        name: "Meme Battalion",
        concept: "The timeline as a war we enjoy.",
        description: "Stamp + offset. Community meme wars. Native, not stolen-without-credit.",
        mood: "Fast, stupid-smart, volume.",
        palette: "Green field, orange 〽️ as a badge.",
        merch: "Tote. BATTALION. Ugly on purpose, designed on purpose.",
        social: "Meme Battalion drop. Credit the maker.",
        activity: "Meme battles. Community challenge.",
      },
      {
        n: "7.5",
        name: "Dark Hour",
        concept: "After-dark games.",
        description: "Almost-black with one acid slash. Adult chaos. Suggestive, not graphic.",
        mood: "Low light, high risk, funny.",
        palette: "Black, acid slash, orange pip.",
        merch: "Hoodie. Dark. Slash inside the hood.",
        social: "Dark Hour. 18+ in the first line.",
        activity: "Dark Hour games. Keep it in the room.",
      },
      {
        n: "7.6",
        name: "The Gauntlet",
        concept: "The weekly challenge as a course.",
        description: "Checkpoint numbers. Seven obstacles. Sunday finishes what the week started.",
        mood: "Athletic chaos.",
        palette: "Orange course, acid checkpoints.",
        merch: "Joggers. Checkpoint marks at the seam.",
        social: "Today's challenge. The Gauntlet.",
        activity: "Community challenge. Recap the survivors.",
      },
      {
        n: "7.7",
        name: "Wild Card",
        concept: "Anything can happen.",
        description: "A rotating mark. The only promised surprise. The week ends without a script.",
        mood: "Unplanned, designed to look unplanned.",
        palette: "Both accents, 〽️ as the card back.",
        merch: "Tee. A card back of 〽️ pattern.",
        social: "Wild Card. We will not tell you what it is.",
        activity: "Wild Card. Host decides live.",
      },
    ],
  },
];

export const socialTemplates = [
  { id: "announce", name: "Daily announcement", use: "Open the day. Sub-brand name. One line. 〽️." },
  { id: "countdown", name: "Daily countdown", use: "Big Barlow numerals. Slash ticks. Day accent." },
  { id: "reveal", name: "Theme reveal", use: "Motif fills the field. Sub-theme name, not the weekday slogan." },
  { id: "activity", name: "Activity announcement", use: "Verb first. Pull up. Keep type huge." },
  { id: "reminder", name: "Event reminder", use: "Time in mono. Place is the Space or the timeline." },
  { id: "space", name: "X Space announcement", use: "Live ring. LIVE in the day accent. No club-flyer clip-art." },
  { id: "game", name: "Game announcement", use: "One rule. One stake. Motif as the board." },
  { id: "music", name: "Music announcement", use: "Seven bars or a track number. Never a screenshot of an app." },
  { id: "challenge", name: "Community challenge", use: "Gauntlet numbers. How to enter in one line." },
  { id: "winner", name: "Winner announcement", use: "Name them. Make it a poster. The room should screenshot it." },
  { id: "birthday", name: "Birthday / celebration", use: "From the cruise. Portrait optional. 〽️ as the gift wrap." },
  { id: "sponsor", name: "Sponsor / vendor feature", use: "Vendor gets a box. We keep the night. No white backgrounds." },
  { id: "recap", name: "Daily recap", use: "Three lines max. What happened. Who showed up." },
  { id: "week", name: "Weekly recap", use: "Seven pips in day colours. The week as a strip." },
];

export const chatCards = [
  { id: "tonight", line: "Tonight's Cruise", sub: "The room is open.", day: "mon" as DayId },
  { id: "pullup", line: "Pull Up", sub: "Don't narrate it. Come.", day: "tue" as DayId },
  { id: "outside", line: "We Outside", sub: "Timeline to real life.", day: "wed" as DayId },
  { id: "space", line: "Space Starting Soon", sub: "Live ring is turning.", day: "fri" as DayId },
  { id: "game", line: "Game Night", sub: "Bring your chest.", day: "sun" as DayId },
  { id: "take", line: "Drop Your Take", sub: "Hot, not hollow.", day: "sat" as DayId },
  { id: "active", line: "Who's Active?", sub: "Say present.", day: "thu" as DayId },
  { id: "anon", line: "Anonymous Drop", sub: "The box is open.", day: "sat" as DayId },
  { id: "bag", line: "Music Bag", sub: "Two songs. No essay.", day: "fri" as DayId },
  { id: "challenge", line: "Today's Challenge", sub: "Enter or watch. Both are a choice.", day: "sun" as DayId },
];

export const merchSkus = [
  { sku: "Heavyweight tee", spec: "240gsm ring-spun combed cotton, oversized drop shoulder, midnight, one-colour" },
  { sku: "Oversized tee", spec: "Dropped shoulder, back print hero or left-chest spark — never both large" },
  { sku: "Hoodie", spec: "Heavyweight, tonal, embroidery or DTF, print inside hood on night capsules" },
  { sku: "Long sleeve", spec: "Cuff hits, no chest pile-up" },
  { sku: "Cap", spec: "Dad cap or 5-panel, 〽️ side or front, no 3D puff gold" },
  { sku: "Shorts", spec: "Hem mark, no all-over" },
  { sku: "Joggers", spec: "Calf or seam graphic, street not gym-bro" },
  { sku: "Tote", spec: "Heavy cotton, one face type, one face 〽️" },
  { sku: "Backpack", spec: "Small 〽️, no full-bleed photo" },
  { sku: "Sticker pack", spec: "Die-cut, midnight mark + day motif" },
  { sku: "Woven label", spec: "Bone on black, 〽️ + BIG CRUISE, inside garment" },
  { sku: "Mailer", spec: "Black mailer, day-coloured slash, no gold tissue" },
];

export const iconSet = [
  { id: "music", label: "Music" },
  { id: "games", label: "Games" },
  { id: "spaces", label: "Spaces" },
  { id: "jobs", label: "Jobs" },
  { id: "culture", label: "Culture" },
  { id: "community", label: "Community" },
  { id: "dating", label: "Dating" },
  { id: "messages", label: "Messages" },
  { id: "challenges", label: "Challenges" },
  { id: "events", label: "Events" },
  { id: "merch", label: "Merch" },
] as const;

export const production = {
  dpi: 300,
  color: "CMYK for print, sRGB for digital",
  masters: "SVG vector for marks and type. Raster photography as TIFF/PNG.",
  safe: "Keep type and 〽️ inside 5mm safe. Chest print ~280–300mm wide.",
  transparent: "True alpha. Never a checkerboard baked into the file.",
  type: "Convert text to outlines for print PDFs. Keep live text in the brand book.",
  cmyk: {
    midnight: "0, 0, 0, 96",
    danfo: "0, 20, 100, 4",
    burgundy: "20, 90, 70, 40",
    pink: "0, 85, 35, 0",
    rose: "10, 70, 35, 10",
    purple: "60, 85, 0, 10",
    red: "20, 100, 80, 30",
    acid: "30, 0, 90, 0",
  },
};

export const merchBanned = [
  "CRUISE & CONNECT HUB",
  "CRUISE CONNECT HUB",
  "CRUISE CONNECT",
  "MEN CRUSH MONDAY",
  "TITTY TUESDAY",
  "WOMEN CRUSH WEDNESDAY",
  "THROWBACK THURSDAY",
  "NEW MUSIC FRIDAY",
  "FRIDAY PLAYLIST",
  "SECRET MESSAGES SATURDAY",
  "WILD 'N' OUT SUNDAY",
];

export function dayById(id: DayId) {
  return days.find((d) => d.id === id)!;
}
