import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { createChessState, makeMove, type ChessMove, type ChessState } from './rules.ts';
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','content-type':'application/json'};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:cors});
async function user(req:Request){const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)throw Error('Authentication required');const {data,error}=await admin.auth.getUser(token);if(error||!data.user)throw Error('Invalid session');return data.user}
async function profile(uid:string){const {data}=await admin.from('profiles').select('display_name,big_cruise_id').eq('id',uid).maybeSingle();return data||{display_name:'Cruiser',big_cruise_id:null}}
async function session(code:string){const {data:room,error:re}=await admin.from('game_rooms').select('*').eq('code',code).single();if(re||!room)throw Error('Room not found');const {data:players,error:pe}=await admin.from('game_players').select('user_id,display_name,cruise_id,ready').eq('room_code',code).order('joined_at');if(pe)throw pe;const {data:sess,error:se}=await admin.from('game_sessions').select('id,state,version,status').eq('room_code',code).order('started_at',{ascending:false}).limit(1).single();if(se||!sess)throw Error('Match session not found');return{room,players:players||[],sess}}
function publicState(state:ChessState,players:{user_id:string;display_name:string;ready:boolean}[],roomStatus:string){return{...state,status:roomStatus==='open'?'lobby':roomStatus==='live'?'playing':'finished',players:players.map((p,i)=>({id:p.user_id,displayName:p.display_name,color:i===0?'white':'black',ready:p.ready}))}}
async function recordResult(state:ChessState,matchId:string,code:string,players:{user_id:string}[]){const winner=state.result==='white_wins'?'white':state.result==='black_wins'?'black':null;for(const [i,p] of players.entries()){const won=winner!==null&&((i===0?'white':'black')===winner);const result=winner===null?'draw':won?'win':'loss';await admin.from('game_results').insert({session_id:matchId,user_id:p.user_id,game:'chess',result,hosted:false});await admin.from('game_matches').insert({user_id:p.user_id,game:'chess',result,hosted:false,room_code:code});await admin.from('game_stats').upsert({user_id:p.user_id,game:'chess',played:1,won:won?1:0,last_played:new Date().toISOString()},{onConflict:'user_id,game'})}}
Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response('',{headers:cors});const u=await user(req);const b=await req.json().catch(()=>({}));const action=String(b.action||'');
if(action==='create'){const pr=await profile(u.id);const code=Math.random().toString(36).slice(2,6).toUpperCase();const room=await admin.from('game_rooms').insert({code,game:'chess',host_user_id:u.id,host_name:pr.display_name,kind:'private',status:'open',seats:2,filled:1}).select().single();if(room.error)throw room.error;const player=await admin.from('game_players').insert({room_code:code,user_id:u.id,display_name:pr.display_name,cruise_id:pr.big_cruise_id,is_host:true,ready:true});if(player.error)throw player.error;const sess=await admin.from('game_sessions').insert({room_code:code,game:'chess',host_user_id:u.id,status:'open',state:null,version:0}).select('id').single();if(sess.error)throw sess.error;return json({code,matchId:sess.data.id,status:'lobby'})}
const code=String(b.code||'').toUpperCase();const loaded=await session(code);if(action==='join'){if(loaded.room.status!=='open')throw Error('Match already started');if(loaded.players.length>=2&&!loaded.players.some(p=>p.user_id===u.id))throw Error('Room is full');const pr=await profile(u.id);const ins=await admin.from('game_players').upsert({room_code:code,user_id:u.id,display_name:pr.display_name,cruise_id:pr.big_cruise_id,is_host:false,ready:false},{onConflict:'room_code,user_id'});if(ins.error)throw ins.error;return json({code,status:'lobby'})}
if(!loaded.players.some(p=>p.user_id===u.id))throw Error('You are not in this room');let state:ChessState=loaded.sess.state||createChessState();const players=loaded.players.map(p=>({...p,ready:Boolean(p.ready)}));
if(action==='state')return json(publicState(state,players,loaded.room.status));
if(action==='ready'){const q=await admin.from('game_players').update({ready:Boolean(b.ready)}).eq('room_code',code).eq('user_id',u.id);if(q.error)throw q.error;return json(publicState(state,players.map(p=>p.user_id===u.id?{...p,ready:Boolean(b.ready)}:p),loaded.room.status))}
if(action==='start'){if(state.result!=='playing'||loaded.room.status!=='open')throw Error('Match already started');if(players.length!==2||!players.every(p=>p.ready))throw Error('Two ready players are required');state=createChessState();const update=await admin.from('game_sessions').update({status:'live',state,version:loaded.sess.version+1}).eq('id',loaded.sess.id).eq('version',loaded.sess.version).select().maybeSingle();if(update.error||!update.data)throw Error('Game changed; refresh and try again');await admin.from('game_rooms').update({status:'live',updated_at:new Date().toISOString()}).eq('code',code);return json(publicState(state,players,'live'))}
if(action==='move'){if(loaded.room.status!=='live')throw Error('Match has not started');const index=players.findIndex(p=>p.user_id===u.id);if((state.turn==='white'&&index!==0)||(state.turn==='black'&&index!==1))throw Error('Not your turn');const raw=b.move||{};const move:ChessMove={from:{row:Number(raw.from?.row),col:Number(raw.from?.col)},to:{row:Number(raw.to?.row),col:Number(raw.to?.col)},promotion:raw.promotion};state=makeMove(state,move);const update=await admin.from('game_sessions').update({state,status:state.result==='playing'?'live':'ended',version:loaded.sess.version+1,ended_at:state.result==='playing'?null:new Date().toISOString()}).eq('id',loaded.sess.id).eq('version',loaded.sess.version).select().maybeSingle();if(update.error||!update.data)throw Error('Game changed; refresh and try again');if(state.result!=='playing')await recordResult(state,loaded.sess.id,code,players);return json(publicState(state,players,'live'))}
if(action==='leave'){await admin.from('game_players').delete().eq('room_code',code).eq('user_id',u.id);return json({left:true})}
if(action==='rematch'){if(state.result==='playing')throw Error('Finish the match first');state=createChessState();const update=await admin.from('game_sessions').update({state,status:'live',version:loaded.sess.version+1,ended_at:null}).eq('id',loaded.sess.id).eq('version',loaded.sess.version).select().maybeSingle();if(update.error||!update.data)throw Error('Game changed; refresh and try again');return json(publicState(state,players,'live'))}
throw Error('Unknown action');}catch(e){return json({error:e instanceof Error?e.message:'Unexpected error'},400)}});
