import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','content-type':'application/json'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:cors});
type Game='tictactoe'|'connect4'|'draw'|'werewolf'|'codenames'|'word-guess'|'karaoke'|'truth-or-dare'|'kahoot';
const partyGames=['werewolf','codenames','word-guess','karaoke','truth-or-dare','kahoot'];
const partyRounds:Record<string,{prompt:string;options:string[];answer:string;category:string}>={werewolf:{prompt:'The village heard a howl near the docks. Who do you investigate?',options:['The quiet sailor','The loud captain','The new guest'],answer:'The quiet sailor',category:'NIGHT INVESTIGATION'},codenames:{prompt:'Your clue is OCEAN. Which word belongs to your team?',options:['WAVE','MOUSE','CROWN'],answer:'WAVE',category:'TEAM CLUE'},'word-guess':{prompt:'Guess the five-letter word from the clue: something you ride on water.',options:['BOARD','TRAIN','CLOUD'],answer:'BOARD',category:'WORD GUESS'},karaoke:{prompt:'Pick the next BIG CRUISE karaoke energy.',options:['90s R&B','Afrobeats','Dancehall'],answer:'Afrobeats',category:'KARAOKE ROUND'},'truth-or-dare':{prompt:'Choose your Cruise challenge.',options:['Truth: funniest travel story','Dare: dance for 10 seconds','Truth: secret talent'],answer:'Dare: dance for 10 seconds',category:'TRUTH OR DARE'},kahoot:{prompt:'Which game has four tokens racing home?',options:['Ludo','Chess','Codenames'],answer:'Ludo',category:'CRUISE QUIZ'}};
const partyState=(game:string)=>({game,phase:'playing',round:1,roundData:partyRounds[game],submissions:[],scores:{}});
const isParty=(game:string)=>partyGames.includes(game);type Mark='X'|'O';type DrawStroke={x:number;y:number;color:string;size:number;tool:'begin'|'move'|'end'|'clear'};
type State={game:Game;phase?:'lobby'|'playing'|'finished';board?:((Mark|null)[]|(('R'|'Y')|null)[][]);turn?:Mark|'R'|'Y';winner?:Mark|'R'|'Y'|'draw'|null;round?:number;roundData?:{prompt:string;options:string[];answer:string;category:string};submissions?:{playerId:string;answer:string;score:number}[];scores?:Record<string,number>;drawerId?:string|null;word?:string|null;roundActive?:boolean;strokes?:DrawStroke[];guesses?:{playerId:string;text:string}[];winnerId?:string|null};
const words=['cat','house','tree','car','guitar','pizza','robot','sun','dragon','bicycle'];
async function auth(req:Request){const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!t)throw Error('Authentication required');const {data,error}=await admin.auth.getUser(t);if(error||!data.user)throw Error('Invalid session');return data.user}
async function profile(id:string){const {data}=await admin.from('profiles').select('display_name,big_cruise_id').eq('id',id).maybeSingle();return data||{display_name:'Cruiser',big_cruise_id:null}}
async function load(code:string){const {data:room,error:re}=await admin.from('game_rooms').select('*').eq('code',code).single();if(re||!room)throw Error('Room not found');const {data:players,error:pe}=await admin.from('game_players').select('user_id,display_name,cruise_id,ready,is_host').eq('room_code',code).order('joined_at');if(pe)throw pe;const {data:sess,error:se}=await admin.from('game_sessions').select('id,state,version,status,game').eq('room_code',code).order('started_at',{ascending:false}).limit(1).single();if(se||!sess)throw Error('Match session not found');return{room,players:players||[],sess}}
const emptyTic=():State=>({game:'tictactoe',board:Array(9).fill(null),turn:'X',winner:null});
const emptyConnect=():State=>({game:'connect4',board:Array.from({length:6},()=>Array(7).fill(null)),turn:'R',winner:null});
const emptyDraw=():State=>({game:'draw',round:0,drawerId:null,word:null,roundActive:false,strokes:[],guesses:[],winnerId:null});
const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function ticWinner(b:(Mark|null)[]){for(const [a,c,d] of lines)if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'draw':null}
function ticMove(s:State,i:number,m:Mark){const b=s.board as (Mark|null)[];if(s.winner)throw Error('Match is complete');if(s.turn!==m||!Number.isInteger(i)||i<0||i>8||b[i])throw Error('Illegal move');b[i]=m;s.turn=m==='X'?'O':'X';s.winner=ticWinner(b)}
function connectWinner(b:(('R'|'Y')|null)[][]){const dirs=[[0,1],[1,0],[1,1],[1,-1]];for(let r=0;r<6;r++)for(let c=0;c<7;c++){const p=b[r][c];if(!p)continue;for(const [dr,dc] of dirs){let n=1;for(let k=1;k<4;k++)if(b[r+dr*k]?.[c+dc*k]===p)n++;else break;if(n>=4)return p}}return b.every(r=>r.every(Boolean))?'draw':null}
function connectMove(s:State,c:number,m:'R'|'Y'){const b=s.board as (('R'|'Y')|null)[][];if(s.winner)throw Error('Match is complete');if(s.turn!==m||!Number.isInteger(c)||c<0||c>6)throw Error('Illegal column');let row=-1;for(let r=5;r>=0;r--)if(!b[r][c]){row=r;break}if(row<0)throw Error('Column is full');b[row][c]=m;s.turn=m==='R'?'Y':'R';s.winner=connectWinner(b)}
function startDraw(s:State,drawerId:string){s.round=(s.round||0)+1;s.drawerId=drawerId;s.word=words[Math.floor(Math.random()*words.length)];s.roundActive=true;s.strokes=[];s.guesses=[];s.winnerId=null}
function publicState(s:State,uid:string,players:unknown[]){const out={...s,players};if(s.game==='draw'&&s.drawerId!==uid)out.word=null;return out}
async function save(code:string,id:string,version:number,s:State,status:'open'|'live'|'ended'){const q=await admin.from('game_sessions').update({state:s,status,version:version+1,ended_at:status==='ended'?new Date().toISOString():null}).eq('id',id).eq('version',version).select().maybeSingle();if(q.error||!q.data)throw Error('Game changed; refresh and try again')}
Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response('',{headers:cors});const u=await auth(req),b=await req.json().catch(()=>({})),action=String(b.action||'');
 if(action==='create'){const game=String(b.game) as Game;if(!['tictactoe','connect4','draw',...partyGames].includes(game))throw Error('Unknown game');const p=await profile(u.id),code=Math.random().toString(36).slice(2,8).toUpperCase();const kind=String(b.kind||'private')==='public'?'public':'private';const r=await admin.from('game_rooms').insert({code,game,host_user_id:u.id,host_name:p.display_name,kind,status:'open',seats:game==='draw'?8:2,filled:1}).select().single();if(r.error)throw r.error;const gp=await admin.from('game_players').insert({room_code:code,user_id:u.id,display_name:p.display_name,cruise_id:p.big_cruise_id,is_host:true,ready:true});if(gp.error)throw gp.error;const ss=await admin.from('game_sessions').insert({room_code:code,game,host_user_id:u.id,status:'open',state:game==='tictactoe'?emptyTic():game==='connect4'?emptyConnect():game==='draw'?emptyDraw():partyState(game),version:0}).select('id').single();if(ss.error)throw ss.error;return json({code,matchId:ss.data.id,game,status:'lobby',kind})}
 const code=String(b.code||'').toUpperCase();const loaded=await load(code);if(!['tictactoe','connect4','draw',...partyGames].includes(loaded.room.game))throw Error('Unsupported game');if(action==='join'){if(loaded.room.status!=='open')throw Error('Match already started');if(loaded.players.length>=Number(loaded.room.seats||2)&&!loaded.players.some(p=>p.user_id===u.id))throw Error('Room is full');const p=await profile(u.id),q=await admin.from('game_players').upsert({room_code:code,user_id:u.id,display_name:p.display_name,cruise_id:p.big_cruise_id,is_host:false,ready:false},{onConflict:'room_code,user_id'});if(q.error)throw q.error;return json({code,game:loaded.room.game,status:'lobby'})}
 if(!loaded.players.some(p=>p.user_id===u.id))throw Error('You are not in this room');const game=loaded.room.game as Game;let s=(loaded.sess.state|| (game==='tictactoe'?emptyTic():game==='connect4'?emptyConnect():game==='draw'?emptyDraw():partyState(game))) as State;const players=loaded.players.map((p,i)=>({id:p.user_id,displayName:p.display_name,ready:Boolean(p.ready),score:Number((s as any).scores?.[p.user_id]||0),role:game==='tictactoe'?(i?'O':'X'):game==='connect4'?(i?'Y':'R'):undefined,isDrawer:s.drawerId===p.user_id}));
 if(game!=='draw'&&loaded.players.length>=2&&s.winner===null&&loaded.room.status==='open'){s=game==='tictactoe'?emptyTic():emptyConnect();await admin.from('game_rooms').update({status:'live',filled:loaded.players.length}).eq('code',code);await save(code,loaded.sess.id,loaded.sess.version,s,'live');}
 if(isParty(game)&&loaded.players.length>=2&&s.phase==='lobby'){s=partyState(game);await admin.from('game_rooms').update({status:'live',filled:loaded.players.length}).eq('code',code);await save(code,loaded.sess.id,loaded.sess.version,s,'live');}
 if(game==='draw'&&loaded.players.length>=2&&!s.roundActive){startDraw(s,loaded.players[0].user_id);await admin.from('game_rooms').update({status:'live',filled:loaded.players.length}).eq('code',code);await save(code,loaded.sess.id,loaded.sess.version,s,'live');}
 if(action==='state')return json(publicState(s,u.id,players));
 if(action==='submit'){if(!isParty(game))throw Error('Submit is only available for party games');if(s.phase!=='playing')throw Error('Round is complete');const answer=String(b.answer||'').slice(0,120);if(!partyRounds[game].options.includes(answer))throw Error('Choose one of the listed options');const score=answer===partyRounds[game].answer?100:0;s.submissions=[...(s.submissions||[]),{playerId:u.id,answer,score}];s.scores={...(s.scores||{}),[u.id]:Number((s.scores||{})[u.id]||0)+score};if(loaded.players.length<2||s.submissions.length>=loaded.players.length){s.phase='finished';const best=Math.max(...loaded.players.map(p=>Number((s.scores||{})[p.user_id]||0)));s.winnerId=loaded.players.find(p=>Number((s.scores||{})[p.user_id]||0)===best)?.user_id||null;}await save(code,loaded.sess.id,loaded.sess.version,s,s.phase==='finished'?'ended':'live');}
 if(action==='move'){if(game==='tictactoe'){const i=players.findIndex(p=>p.id===u.id);if(i<0||!['X','O'].includes(String(players[i].role)))throw Error('Role unavailable');ticMove(s,Number(b.index),players[i].role as Mark)}else if(game==='connect4'){const i=players.findIndex(p=>p.id===u.id);connectMove(s,Number(b.column),players[i].role as 'R'|'Y')}else throw Error('Use draw or guess');await save(code,loaded.sess.id,loaded.sess.version,s,s.winner?'ended':'live');}
 if(action==='draw'){if(game!=='draw'||s.drawerId!==u.id||!s.roundActive)throw Error('Only the active drawer can draw');const d=b.stroke as DrawStroke;if(!d||!['begin','move','end','clear'].includes(d.tool)||!Number.isFinite(Number(d.x))||!Number.isFinite(Number(d.y))||Number(d.size)<1||Number(d.size)>40)throw Error('Invalid stroke');s.strokes=[...(s.strokes||[]),{x:Number(d.x),y:Number(d.y),color:String(d.color||'#ffd400').slice(0,16),size:Number(d.size),tool:d.tool}];await save(code,loaded.sess.id,loaded.sess.version,s,'live')}
 if(action==='guess'){if(game!=='draw'||!s.roundActive||s.drawerId===u.id||typeof b.text!=='string'||!b.text.trim())throw Error('Guess not allowed');const text=String(b.text).trim().slice(0,80);s.guesses=[...(s.guesses||[]),{playerId:u.id,text}];if(text.toLowerCase()===String(s.word).toLowerCase()){s.roundActive=false;s.winnerId=u.id}await save(code,loaded.sess.id,loaded.sess.version,s,s.roundActive?'live':'ended')}
 if(action==='new-round'){if(game!=='draw'||loaded.players[0].user_id!==u.id)throw Error('Only the room host can start a new round');const idx=loaded.players.findIndex(p=>p.user_id===s.drawerId);startDraw(s,loaded.players[(idx+1+loaded.players.length)%loaded.players.length].user_id);await save(code,loaded.sess.id,loaded.sess.version,s,'live')}
 if(action==='replay'){if(isParty(game))s=partyState(game);else if(game==='draw')s=emptyDraw();else s=game==='tictactoe'?emptyTic():emptyConnect();await save(code,loaded.sess.id,loaded.sess.version,s,'open');await admin.from('game_rooms').update({status:'open'}).eq('code',code)}
 if(action==='leave'){await admin.from('game_players').delete().eq('room_code',code).eq('user_id',u.id);return json({left:true})}
 return json(publicState(s,u.id,players));
 }catch(e){return json({error:e instanceof Error?e.message:'Unexpected error'},400)}});
