import React, { useEffect, useState } from 'react';
import { connectDrop, createConnectState, createTicState, ticMove, type ConnectState, type TicState } from '../lib/games/onmuga/rules';

type Props={game:'tictactoe'|'connect4';onBack:()=>void};
const ticPick=(s:TicState)=>s.board.findIndex(cell=>!cell);
const connectPick=(s:ConnectState)=>{for(let c=0;c<7;c++)if(!s.board[0][c])return c;return -1};
function BoardSolo({game,onBack}:Props){
 const [tic,setTic]=useState<TicState>(()=>createTicState()); const [connect,setConnect]=useState<ConnectState>(()=>createConnectState());
 const state=game==='tictactoe'?tic:connect; const finished=Boolean(state.winner);
 useEffect(()=>{if(finished||state.turn!=='O'&&state.turn!=='Y')return;const timer=window.setTimeout(()=>{try{if(game==='tictactoe')setTic(prev=>ticMove(prev,ticPick(prev),'O'));else setConnect(prev=>connectDrop(prev,connectPick(prev),'Y'))}catch{}},450);return()=>window.clearTimeout(timer)},[game,finished,state.turn]);
 const reset=()=>{setTic(createTicState());setConnect(createConnectState())};
 if(game==='tictactoe')return <section className="onmuga-shell solo-classic-shell"><div className="room-head"><div><span className="eyebrow">SOLO TIC-TAC-TOE</span><h1>Three in a row.</h1><p className="muted">{finished?state.winner==='draw'?'Draw game':`${state.winner==='X'?'You':'Cruise Bot'} win`:state.turn==='X'?'Your turn':'Cruise Bot is thinking…'}</p></div><button onClick={onBack}>Exit</button></div><div className="ttt-board">{tic.board.map((v,i)=><button key={i} disabled={Boolean(v)||Boolean(tic.winner)||tic.turn!=='X'} onClick={()=>setTic(prev=>ticMove(prev,i,'X'))}>{v||''}</button>)}</div>{finished&&<button className="primary" onClick={reset}>Play again</button>}</section>;
 return <section className="onmuga-shell solo-classic-shell"><div className="room-head"><div><span className="eyebrow">SOLO CONNECT FOUR</span><h1>Drop four.</h1><p className="muted">{finished?connect.winner==='draw'?'Draw game':`${connect.winner==='R'?'You':'Cruise Bot'} win`:connect.turn==='R'?'Your turn':'Cruise Bot is thinking…'}</p></div><button onClick={onBack}>Exit</button></div><div className="connect-board"><div className="connect-drops">{Array.from({length:7},(_,c)=><button key={c} disabled={Boolean(connect.winner)||connect.turn!=='R'} onClick={()=>setConnect(prev=>connectDrop(prev,c,'R'))}>▼</button>)}</div>{connect.board.map((row,r)=>row.map((v,c)=><div key={`${r}-${c}`} className={`connect-slot ${v==='R'?'red':''} ${v==='Y'?'gold':''}`}>{v&&<span>{v}</span>}</div>))}</div>{finished&&<button className="primary" onClick={reset}>Play again</button>}</section>;
}
export function BoardModeGate({game,user,multiplayer}:{game:Props['game'];user:{id:string};multiplayer:React.ReactNode}){const [mode,setMode]=useState<'choose'|'solo'|'multi'>('choose');if(mode==='solo')return <><button className="link" onClick={()=>setMode('choose')}>← Game modes</button><BoardSolo game={game} onBack={()=>setMode('choose')}/></>;if(mode==='multi')return <>{multiplayer}</>;return <section className="onmuga-shell matchmaking-shell"><span className="eyebrow">BIG CRUISE ARCADE · {game==='tictactoe'?'TIC-TAC-TOE':'CONNECT FOUR'}</span><h1>How do you want to play?</h1><p className="muted">Practice against Cruise Bot or open a realtime room for users.</p><div className="matchmaking-options"><button className="primary" onClick={()=>setMode('solo')}><strong>Solo with Cruise Bot</strong><small>Fast local practice</small></button><button onClick={()=>setMode('multi')}><strong>Multiplayer room</strong><small>Create or join with a room code</small></button></div></section>}
