import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createChessState, legalMoves, makeMove, type ChessMove, type ChessState } from '../lib/games/chess/rules';
import { createLudoState, currentPlayer as ludoCurrent, legalPieceIds, movePiece, rollDice, type LudoState } from '../lib/games/ludo/rules';
import { callUno, canPlayCard, createGame, currentPlayer as unoCurrent, drawCard, getLegalPlays, playCard, topCard, type UnoColor, type UnoState } from '../lib/games/uno/rules';
import { chessBotMove, ludoBotPiece, unoBotCard, type BotDifficulty } from '../lib/games/bots';

export type ClassicGame = 'ludo'|'chess'|'uno'|'draw-it-out';
type User={id:string};
const glyphs={king:'♚',queen:'♛',rook:'♜',bishop:'♝',knight:'♞',pawn:'♟'} as const;

export function ClassicGameGate({game,user,multiplayer}:{game:ClassicGame;user:User;multiplayer:React.ReactNode}){
 const [mode,setMode]=useState<'choose'|'solo'|'multi'>('choose');const [difficulty,setDifficulty]=useState<BotDifficulty>('cruise');
 if(mode==='solo')return <><button className="link" onClick={()=>setMode('choose')}>← Game modes</button><ClassicSoloGame game={game} user={user} difficulty={difficulty}/></>;
 if(mode==='multi')return <>{multiplayer}</>;
 const title=game==='draw-it-out'?'Draw It Out':game.toUpperCase();
 return <section className="onmuga-shell matchmaking-shell"><span className="eyebrow">BIG CRUISE ARCADE · {title}</span><h1>How do you want to play?</h1><p className="muted">Start a solo match with Cruise Bot or open the realtime room flow for your crew.</p><div className="matchmaking-options"><button className="primary" onClick={()=>setMode('solo')}><strong>Solo with Cruise Bot</strong><small>Mobile-first practice with adjustable difficulty</small></button><button onClick={()=>setMode('multi')}><strong>Multiplayer room</strong><small>Invite friends or join a live room</small></button></div><div className="bot-difficulty-grid compact-bot-grid">{(['easy','cruise','pro','elite'] as BotDifficulty[]).map(level=><button key={level} className={difficulty===level?'selected':''} onClick={()=>setDifficulty(level)}><strong>{level[0].toUpperCase()+level.slice(1)}</strong><small>{level==='easy'?'Relaxed':level==='cruise'?'Balanced':level==='pro'?'Sharp':'Elite'}</small></button>)}</div></section>;
}

export function ClassicSoloGame({game,user,difficulty}:{game:ClassicGame;user:User;difficulty:BotDifficulty}){
 if(game==='ludo')return <SoloLudo user={user} difficulty={difficulty}/>;
 if(game==='chess')return <SoloChess user={user} difficulty={difficulty}/>;
 if(game==='uno')return <SoloUno user={user} difficulty={difficulty}/>;
 return <SoloDraw difficulty={difficulty}/>;
}

function SoloLudo({user,difficulty}:{user:User;difficulty:BotDifficulty}){
 const [state,setState]=useState<LudoState>(()=>createLudoState({matchId:'solo',roomId:'solo',players:[{id:user.id,displayName:'You',color:'red'},{id:'bot',displayName:'Cruise Bot',color:'green'}],status:'playing'}));
 const [error,setError]=useState('');const me=state.players[0];const bot=state.players[1];
 const commit=(action:()=>void)=>{try{setError('');action();setState({...state,players:state.players.map(p=>({...p,pieces:p.pieces.map(piece=>({...piece}))}))})}catch(e){setError(e instanceof Error?e.message:'Move unavailable')}};
 useEffect(()=>{if(state.status==='finished'||ludoCurrent(state).id!==bot.id)return;const timer=setTimeout(()=>commit(()=>{if(state.phase==='await_roll')rollDice(state,bot.id);else {const id=ludoBotPiece(state,bot.id,difficulty);if(id)movePiece(state,bot.id,id)}}),700);return()=>clearTimeout(timer)},[state.currentPlayerIndex,state.phase,state.dice,state.status]);
 const roll=()=>commit(()=>rollDice(state,user.id));const move=(id:string)=>commit(()=>movePiece(state,user.id,id));const legal=legalPieceIds(state,user.id);
 return <section className="onmuga-shell solo-classic-shell"><div className="room-head"><div><span className="eyebrow">SOLO LUDO · {difficulty.toUpperCase()}</span><h1>Race home.</h1><p className="muted">{state.status==='finished'?`${state.winnerId===user.id?'You win':'Cruise Bot wins'} · match complete`:ludoCurrent(state).id===user.id?state.phase==='await_roll'?'Your roll':'Choose a highlighted piece':'Cruise Bot is thinking…'}</p></div></div><div className="player-strip"><span className="active">You · {me.pieces.filter(p=>p.steps===58).length}/4 home</span><span>Cruise Bot · {bot.pieces.filter(p=>p.steps===58).length}/4 home</span></div><div className="ludo-mini-board">{state.players.flatMap(player=>player.pieces.map(piece=><button key={piece.id} className={`mini-piece ${player.color} ${legal.includes(piece.id)?'selectable':''}`} disabled={!legal.includes(piece.id)} onClick={()=>move(piece.id)} aria-label={`${player.displayName} piece at ${piece.steps}`}>{piece.steps===-1?'•':piece.steps===58?'✓':piece.steps}</button>))}</div><div className="controls"><button className="primary" disabled={ludoCurrent(state).id!==user.id||state.phase!=='await_roll'||state.status==='finished'} onClick={roll}>{state.dice?`Rolled ${state.dice}`:'Roll dice'}</button></div>{error&&<p className="error" role="alert">{error}</p>}</section>;
}

function SoloChess({user,difficulty}:{user:User;difficulty:BotDifficulty}){
 const [state,setState]=useState<ChessState>(()=>createChessState());const [selected,setSelected]=useState<{row:number;col:number}|null>(null);const [error,setError]=useState('');
 useEffect(()=>{if(state.turn!=='black'||state.result!=='playing')return;const timer=setTimeout(()=>{try{const move=chessBotMove(state,'black',difficulty);if(move)setState(makeMove(state,move))}catch(e){setError(e instanceof Error?e.message:'Bot move unavailable')}},700);return()=>clearTimeout(timer)},[state.turn,state.result]);
 const moves=selected?legalMoves(state,selected):[];const choose=(row:number,col:number)=>{if(state.turn!=='white'||state.result!=='playing')return;const target=moves.find(move=>move.to.row===row&&move.to.col===col);if(target){try{setState(makeMove(state,target));setSelected(null)}catch(e){setError(e instanceof Error?e.message:'Illegal move')}return}if(state.board[row][col]?.color==='white')setSelected({row,col});else setSelected(null)};
 return <section className="onmuga-shell solo-classic-shell"><div className="room-head"><div><span className="eyebrow">SOLO CHESS · {difficulty.toUpperCase()}</span><h1>Think ahead.</h1><p className="muted">{state.result==='playing'?(state.turn==='white'?'Your move':'Cruise Bot is thinking…'):state.result.replaceAll('_',' ')}</p></div></div><div className="chess-board" role="grid" aria-label="Solo chess board">{state.board.map((row,r)=>row.map((piece,c)=>{const legal=moves.some(m=>m.to.row===r&&m.to.col===c);return <button role="gridcell" key={`${r}-${c}`} className={`chess-square ${(r+c)%2?'dark':'light'} ${selected?.row===r&&selected.col===c?'selected':''} ${legal?'legal':''}`} onClick={()=>choose(r,c)}>{piece&&<span className={`chess-piece ${piece.color}`}>{glyphs[piece.kind]}</span>}</button>}))}</div>{error&&<p className="error" role="alert">{error}</p>}</section>;
}

function SoloUno({user,difficulty}:{user:User;difficulty:BotDifficulty}){
 const [state,setState]=useState<UnoState>(()=>createGame([{id:user.id,displayName:'You',ready:true},{id:'bot',displayName:'Cruise Bot',ready:true}]));const [error,setError]=useState('');const me=state.players[0];const mine=state.currentPlayerIndex===0;
 useEffect(()=>{if(!state||state.phase!=='playing'||state.currentPlayerIndex===0)return;const timer=setTimeout(()=>{try{let next=state;const bot=unoCurrent(next);const card=unoBotCard(getLegalPlays(next,bot.id),difficulty);if(card)next=playCard(next,bot.id,card.id,card.color==='wild'?'red':undefined);else next=drawCard(next,bot.id);if(next.pendingUnoPlayerId==='bot')next=callUno(next,'bot');setState({...next,players:next.players.map(p=>({...p,hand:[...p.hand]}))})}catch(e){setError(e instanceof Error?e.message:'Bot move unavailable')}},800);return()=>clearTimeout(timer)},[state.currentPlayerIndex,state.phase,state.discardPile.length]);
 const play=(id:string)=>{try{let next=playCard(state,user.id,id,'red');if(next.pendingUnoPlayerId===user.id)next=callUno(next,user.id);setState({...next,players:next.players.map(p=>({...p,hand:[...p.hand]}))})}catch(e){setError(e instanceof Error?e.message:'Choose a playable card')}};const draw=()=>{try{const next=drawCard(state,user.id);setState({...next,players:next.players.map(p=>({...p,hand:[...p.hand]}))})}catch(e){setError(e instanceof Error?e.message:'Draw unavailable')}};const legal=getLegalPlays(state,user.id);
 return <section className="onmuga-shell solo-classic-shell"><div className="room-head"><div><span className="eyebrow">SOLO UNO · {difficulty.toUpperCase()}</span><h1>Play your hand.</h1><p className="muted">{state.phase==='finished'?`${state.winnerId===user.id?'You win':'Cruise Bot wins'}`:mine?'Your turn':'Cruise Bot is thinking…'}</p></div></div><div className="uno-solo-center"><div className="big-card" style={{background:topCard(state).color==='wild'?'#222':topCard(state).color}}>{topCard(state).kind==='number'?topCard(state).value:topCard(state).kind}</div><button className="draw-pile" onClick={draw} disabled={!mine||state.phase!=='playing'}>DRAW</button></div><div className="hand solo-hand">{me.hand.map(card=><button key={card.id} className="uno-card" disabled={!mine||!legal.some(item=>item.id===card.id)} onClick={()=>play(card.id)} style={{background:card.color==='wild'?'#222':card.color}}>{card.kind==='number'?card.value:card.kind}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}</section>;
}

function SoloDraw({difficulty}:{difficulty:BotDifficulty}){
 const canvasRef=useRef<HTMLCanvasElement|null>(null);const [guess,setGuess]=useState('');const [result,setResult]=useState('');const target='sun';
 useEffect(()=>{const canvas=canvasRef.current;const ctx=canvas?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,700,420);ctx.strokeStyle='#ffd400';ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.arc(350,210,70,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(350+Math.cos(a)*95,210+Math.sin(a)*95);ctx.lineTo(350+Math.cos(a)*135,210+Math.sin(a)*135);ctx.stroke()}},[]);
 const submit=()=>setResult(guess.trim().toLowerCase()===target?'Correct — you beat Cruise Bot.':`Cruise Bot wins this ${difficulty} round. The word was SUN.`);
 return <section className="onmuga-shell solo-classic-shell"><div className="room-head"><div><span className="eyebrow">SOLO DRAW IT OUT · {difficulty.toUpperCase()}</span><h1>Guess the sketch.</h1><p className="muted">Cruise Bot is drawing. Type your guess before the timer runs out.</p></div></div><canvas ref={canvasRef} width={700} height={420} className="draw-canvas" aria-label="Cruise Bot drawing"/><div className="guess-row"><input value={guess} onChange={e=>setGuess(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit()}} placeholder="What is Cruise Bot drawing?"/><button className="primary" onClick={submit} disabled={!guess.trim()}>Guess</button></div>{result&&<div className="result-banner">{result}</div>}</section>;
}
