import React, { useState } from 'react';
import { touchFeedback } from '../lib/feedback';

type CommunityTab='feed'|'challenges'|'leaderboards';
const posts=[
 {handle:'@thecruiseclub',avatar:'C',time:'8m',text:'Friday room is live. Pull up if your playlist has range.',reactions:{'🔥':128,'😂':24,'💯':51},comments:18},
 {handle:'@moyo.moves',avatar:'M',time:'24m',text:'Just cleared a clean sweep on Chess. Who is taking the seat?',reactions:{'👏':42,'🔥':31,'💯':12},comments:9},
 {handle:'@lagosafterdark',avatar:'L',time:'1h',text:'The best thing about BIG CRUISE is that nobody stays a spectator for long.',reactions:{'❤️':88,'🔥':67,'😂':10},comments:22},
];
const leaders=[['FX〽️','1,284 XP','TOP 1%'],['Moyo Moves','1,110 XP','TOP 3%'],['Cruise Club','982 XP','TOP 5%'],['Seyi Plays','864 XP','TOP 8%']];
export function CommunityHub(){const [tab,setTab]=useState<CommunityTab>('feed');const [liked,setLiked]=useState<Record<string,boolean>>({});return <main className="page community-page"><section className="community-hero"><span className="eyebrow">THE CRUISE · COMMUNITY</span><h1>Pull up. Say something.</h1><p className="muted">The board for wins, hot takes, challenges and the people making the room move.</p><button className="primary" onClick={()=>touchFeedback('success')}>＋ Start a post</button></section><div className="community-tabs" role="tablist">{([['feed','For You'],['challenges','Challenges'],['leaderboards','Leaderboards']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>{touchFeedback('tap');setTab(id)}}>{label}</button>)}</div>{tab==='feed'&&<section className="feed-list" aria-label="Community feed">{posts.map(post=><article className="post-card" key={post.handle}><div className="post-head"><span className="post-avatar">{post.avatar}</span><div><b>{post.handle}</b><small>{post.time} ago · cruising now</small></div><button className="post-more" aria-label={`More options for ${post.handle}`}>•••</button></div><p>{post.text}</p><div className="reaction-row">{Object.entries(post.reactions).map(([emoji,count])=><button key={emoji} className={liked[post.handle+emoji]?'reacted':''} onClick={()=>{touchFeedback('tap');setLiked({...liked,[post.handle+emoji]:!liked[post.handle+emoji]})}}>{emoji} {count+(liked[post.handle+emoji]?1:0)}</button>)}<button>💬 {post.comments}</button><button className="share-post">↗ Share</button></div></article>)}</section>}{tab==='challenges'&&<section className="challenge-list"><article className="challenge-card"><span className="challenge-mark">01</span><div><b>THE CLEAN SWEEP</b><p>Win a match without dropping a round.</p><small>+250 XP · 3 days left</small></div><button className="primary">Accept</button></article><article className="challenge-card"><span className="challenge-mark">02</span><div><b>ROOM STARTER</b><p>Create a room and bring three Cruisers in.</p><small>+150 XP · 5 days left</small></div><button>View</button></article><article className="challenge-card"><span className="challenge-mark">03</span><div><b>PLAY YOUR VIBE</b><p>Play one game and open the BIG CRUISE CONTROL playlist.</p><small>+100 XP · today</small></div><button>Start</button></article></section>}{tab==='leaderboards'&&<section className="leaderboard-card"><div className="podium"><div><strong>2</strong><b>Moyo Moves</b><small>1,110 XP</small></div><div className="podium-first"><strong>1</strong><b>FX〽️</b><small>1,284 XP</small></div><div><strong>3</strong><b>Cruise Club</b><small>982 XP</small></div></div><div className="leader-list">{leaders.map((row,index)=><div key={row[0]}><span>#{index+1}</span><b>{row[0]}</b><small>{row[1]} · {row[2]}</small></div>)}</div></section>}</main>}
