import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { botAnswer, firstRound, scoreAnswer, type PartyGame, type PartyRound } from '../lib/games/party/rules';

type User={id:string};
type Player={id:string;displayName:string;score?:number;ready?:boolean};
type State={game:PartyGame;phase:'lobby'|'playing'|'finished';round:PartyRound;players:Player[];winnerId?:string|null;submissions?:{playerId:string;answer:string;score:number}[]};
const labels:Record<PartyGame,string>={werewolf:'WEREWOLF',codenames:'CODENAMES','word-guess':'WORD GUESS',karaoke:'KARAOKE','truth-or-dare':'TRUTH OR DARE',kahoot:'KAHOOT'};
const apiUrl=()=>`${import.meta.env.VITE_SUPABASE_URL||'https://qdeozgkmrqectbuhetvc.supabase.co'}/functions/v1/onmuga`;

export function CruisePartyGame({game,user}:{game:PartyGame;user:User}){
 const [mode,setMode]=useState<'solo'|'online'|null>(null);const [state,setState]=useState<State|null>(null);const [code,setCode]=useState('');const [joinCode,setJoinCode]=useState('');const [answer,setAnswer]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [roomKind,setRoomKind]=useState<'public'|'private'>('private');
 const online=async(action:string,data:Record<string,unknown>={})=>{const {data:{session}}=await supabase.auth.getSession();const r=await fetch(apiUrl(),{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`,'content-type':'application/json'},body:JSON.stringify({action,code,game,...data})});const j=await r.json();if(!r.ok)throw Error(j.error||'Game request failed');return j};
 const startSolo=()=>{const round=firstRound(game);setMode('solo');setState({game,phase:'playing',round,players:[{id:user.id,displayName:'You',score:0},{id:`bot-${game}`,displayName:'Cruise Bot',score:0}],submissions:[]});setError('')};
 const submitSolo=(value:string)=>{if(!state)return;const mine=scoreAnswer(state.round,value);const bot=botAnswer(state.round);const botScore=scoreAnswer(state.round,bot);const scores=(state.players||[]).map(p=>({...p,score:(p.score||0)+(p.id===user.id?mine:botScore)}));const winnerId=scores[0].score===scores[1].score?null:scores[0].score>scores[1].score?scores[0].id:scores[1].id;setState({...state,phase:'finished',players:scores,winnerId,submissions:[{playerId:user.id,answer:value,score:mine},{playerId:`bot-${game}`,answer:bot,score:botScore}]});setAnswer('')};
 const run=async(action:string,data:Record<string,unknown>={})=>{try{setBusy(true);setError('');const j=await online(action,data);if(j.code)setCode(j.code);if(j.game&&j.round)setState(j as State);else if((action==='create'||action==='join')&&j.code){const s=await online('state',{code:String(j.code)});setState(s as State)}}catch(e){setError(e instanceof Error?e.message:'Game request failed')}finally{setBusy(false)}};
 useEffect(()=>{if(!code||mode!=='online')return;const id=setInterval(()=>void run('state'),1800);return()=>clearInterval(id)},[code,mode]);
 const copyCode=async()=>{try{await navigator.clipboard?.writeText(code);setError('Room code copied')}catch{setError('Share this room code: '+code)}};
 if(!mode)return <section className="onmuga-shell matchmaking-shell"><span className="eyebrow">BIG CRUISE ARCADE · {labels[game]}</span><h1>Find your crew.</h1><p className="muted">Choose a fast mobile match, open a private room, or practice with the Cruise Bot.</p><div className="matchmaking-options"><button className="primary" onClick={()=>{setMode('online');setRoomKind('public')}}><strong>Quick match</strong><small>Open a room and wait for one player</small></button><button onClick={()=>{setMode('online');setRoomKind('private')}}><strong>Private room</strong><small>Invite your crew with a code</small></button><button onClick={startSolo}><strong>Solo with Cruise Bot</strong><small>Instant practice · no waiting</small></button></div></section>;
 if(!state&&mode==='online')return <section className="onmuga-shell matchmaking-shell"><span className="eyebrow">{labels[game]} · MATCHMAKING</span><h1>Get in the room.</h1><div className="matchmaking-card"><span className="matchmaking-step">1 · START A ROOM</span><p>{roomKind==='public'?'Quick match creates an open room for the next available player.':'Create a private room and share the code with your crew.'}</p><button className="primary" onClick={()=>void run('create',{kind:roomKind})} disabled={busy}>{busy?'Opening room…':roomKind==='public'?'Find a player':'Create private room'}</button></div><div className="matchmaking-card"><span className="matchmaking-step">2 · JOIN A ROOM</span><p>Have a code? Enter it below. The layout is optimized for one-handed use.</p><div className="join"><input aria-label="Room code" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="ROOM CODE" maxLength={6}/><button onClick={()=>{setCode(joinCode);void run('join',{code:joinCode})}} disabled={busy||joinCode.length<4}>Join</button></div></div><button className="link" onClick={()=>setMode(null)}>← Choose another mode</button>{error&&<p className="error" role="alert">{error}</p>}</section>;
 if(!state)return null;
 const me=state.players.find(p=>p.id===user.id);const leave=()=>{if(mode==='online')void run('leave');setState(null);setCode('');setMode(null);setAnswer('')};
 if(mode==='online'&&state.phase==='lobby')return <section className="onmuga-shell matchmaking-shell"><div className="room-head"><div><span className="eyebrow">MOBILE LOBBY · {labels[game]}</span><h1>Room ready.</h1><p className="muted">{state.players.length}/2 players · keep this screen open while your crew joins.</p></div><button onClick={leave}>Exit</button></div><div className="room-code-card"><span className="matchmaking-step">ROOM CODE</span><strong>{code}</strong><button onClick={()=>void copyCode()} aria-label="Copy room code">Copy</button></div><div className="lobby-list" aria-label="Players in lobby">{[0,1].map(slot=>{const player=state.players[slot];return <div className="lobby-player" key={player?.id||`empty-${slot}`}><span className={`lobby-avatar ${player?'filled':''}`}>{player?'✓':'+'}</span><span><b>{player?.displayName||'Waiting for player'}</b><small>{player?.id===user.id?'You · connected':player?'Connected':'Share the code to invite them'}</small></span><span className="lobby-status">{player?'READY':'OPEN'}</span></div>})}</div><div className="lobby-footer"><span className="connection-dot" aria-hidden="true"/> {state.players.length<2?'Waiting for another player…':'Starting match…'}</div>{error&&<p className="error" role="alert">{error}</p>}</section>;
 if(state.phase==='finished')return <section className="onmuga-shell"><div className="room-head"><div><span className="eyebrow">{mode==='online'?`ROOM ${code} · `:''}{labels[game]}</span><h1>Round complete.</h1></div><button onClick={leave}>Exit</button></div><div className="result-banner">{state.winnerId?`${state.players.find(p=>p.id===state.winnerId)?.displayName} wins`:'Draw game'}</div><div className="player-strip">{state.players.map(p=><span key={p.id}>{p.displayName} · {p.score||0} pts</span>)}</div><div className="controls"><button className="primary" onClick={()=>mode==='solo'?startSolo():void run('replay')}>Rematch</button></div>{error&&<p className="error" role="alert">{error}</p>}</section>;
 return <section className="onmuga-shell"><div className="room-head"><div><span className="eyebrow">{mode==='online'?`ROOM ${code} · `:''}{labels[game]}</span><h1>{state.round.category}</h1><p className="muted">{mode==='online'?`${state.players.length} players in the room`:'Cruise Bot match'}</p></div><button onClick={leave}>Exit</button></div><div className="player-strip">{state.players.map(p=><span key={p.id}>{p.displayName} · {p.score||0} pts</span>)}</div><div className="party-prompt"><h2>{state.round.prompt}</h2><div className="party-options">{state.round.options.map(option=><button key={option} className={answer===option?'selected':''} onClick={()=>setAnswer(option)}>{option}</button>)}</div></div><div className="controls"><button className="primary" disabled={!answer||busy} onClick={()=>mode==='solo'?submitSolo(answer):void run('submit',{answer})}>Lock answer</button></div>{me&&<p className="muted">Your score: {me.score||0}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
