import React, { useEffect, useRef, useState } from 'react';
import { touchFeedback } from '../lib/feedback';

type Detector={detect:(source:ImageBitmapSource)=>Promise<Array<{rawValue?:string}>>};
type Props={email?:string};
export function MemberProfile({email}:Props){const [scanning,setScanning]=useState(false);const [result,setResult]=useState('');const video=useRef<HTMLVideoElement|null>(null);const stream=useRef<MediaStream|null>(null);
 const stop=()=>{stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setScanning(false)};
 const scan=async()=>{touchFeedback('tap');setResult('');const DetectorClass=(window as Window & {BarcodeDetector?:new()=>Detector}).BarcodeDetector;if(!DetectorClass||!navigator.mediaDevices?.getUserMedia){setResult('QR scanning needs a supported mobile browser camera. Use the downloadable QR card instead.');return}try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});setScanning(true);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));if(!video.current)return;video.current.srcObject=stream.current;await video.current.play();const detector=new DetectorClass();const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d');let active=true;const loop=async()=>{if(!active||!video.current||video.current.readyState<2){if(active)requestAnimationFrame(loop);return}canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;ctx?.drawImage(video.current,0,0);try{const hits=await detector.detect(canvas);const value=hits[0]?.rawValue;if(value){active=false;setResult(value);touchFeedback('success');stop();return}}catch{}requestAnimationFrame(loop)};requestAnimationFrame(loop)}catch{setResult('Camera permission was not granted. You can still download the Cruise-ID QR card.');stop()}};
 useEffect(()=>()=>stop(),[]);return <main className="page profile-page"><section className="profile-hero"><span className="eyebrow">MEMBER PROFILE · BIG CRUISE〽</span><h1>FX〽️</h1><p className="muted">@13fxiii · {email||'Big Cruiser'} · Playzone MVP</p><div className="profile-stats"><span><b>LVL 28</b><small>PLAYZONE</small></span><span><b>TOP 1%</b><small>ENGAGEMENT</small></span><span><b>3.1K+</b><small>COMMUNITY</small></span></div></section><img className="cruise-id-preview" src="/assets/cruise-id-front.png" alt="FX Big Cruise member ID card"/><div className="profile-actions"><a className="primary" href="/assets/cruise-id-front.png" download="FX-Big-Cruise-ID-front.png" onClick={()=>touchFeedback('success')}>Download Cruise-ID</a><button onClick={scan}>Scan Cruise-ID</button></div>{scanning&&<div className="scanner-modal"><div className="scanner-card"><div className="room-head"><div><span className="eyebrow">QR SCANNER</span><h2>Point at a Cruise-ID.</h2></div><button onClick={stop}>Close</button></div><video ref={video} className="qr-video" playsInline muted/><p className="muted">Keep the QR code inside the camera frame.</p></div></div>}{result&&<div className="result-banner"><b>Scanned profile</b><br/><a href={result.startsWith('http')?result:undefined}>{result}</a></div>}</main>}
