import React, { useEffect, useMemo, useState } from 'react';
import { touchFeedback } from '../lib/feedback';
import type { CruiseDay } from '../lib/theme';

type Props={theme:CruiseDay;onBack:()=>void};
const QUESTIONS=[
 {q:'Which BIG CRUISE day brings the equalizer bars?',a:['ECHO ERA','PLAY YOUR VIBE','DOMINION STATE','CHAOS CULTURE'],correct:1},
 {q:'How many rooms are in 7 Days of Cruise?',a:['5','6','7','12'],correct:2},
 {q:'Which game is about clues and hidden roles?',a:['Codenames','Ludo','Karaoke','UNO'],correct:0},
 {q:'Which color anchors the BIG CRUISE house identity?',a:['Danfo Yellow','Hot Pink','Acid Green','Cyan'],correct:0},
 {q:'What is the safest multiplayer move when your network drops?',a:['Spam reconnects','Wait for room recovery','Close the app forever','Submit random answers'],correct:1},
];
export function QuizRushGame({theme,onBack}:Props){const [round,setRound]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [score,setScore]=useState(0);const [seconds,setSeconds]=useState(12);const [done,setDone]=useState(false);const question=QUESTIONS[round];useEffect(()=>{if(done||choice!==null)return;const timer=window.setInterval(()=>setSeconds(value=>{if(value<=1){window.clearInterval(timer);setChoice(-1);touchFeedback('error');return 0}return value-1}),1000);return()=>window.clearInterval(timer)},[round,choice,done]);const percent=useMemo(()=>Math.max(0,(seconds/12)*100),[seconds]);const answer=(index:number)=>{if(choice!==null)return;setChoice(index);if(index===question.correct){setScore(value=>value+Math.max(100,seconds*100));touchFeedback('success')}else touchFeedback('error')};const next=()=>{if(round===QUESTIONS.length-1){setDone(true);touchFeedback('success');return}setRound(value=>value+1);setChoice(null);setSeconds(12);touchFeedback('tap')};if(done)return <section className="quiz-rush"><span className="eyebrow">QUIZ RUSH · RESULTS</span><h2>{score>=3500?'CRUISE CHAMPION':'NICE RUN'}</h2><p className="quiz-score">{score.toLocaleString()} <small>POINTS</small></p><p className="muted">You cleared {QUESTIONS.filter((_,i)=>i<round+1).length} questions in {theme.displayName}.</p><button className="primary big" onClick={()=>{setRound(0);setChoice(null);setScore(0);setSeconds(12);setDone(false)}}>PLAY AGAIN</button><button className="link" onClick={onBack}>← Back to games</button></section>;return <section className="quiz-rush"><div className="room-head"><div><span className="eyebrow">QUIZ RUSH · {theme.shortLabel}</span><h2>Question {round+1}/{QUESTIONS.length}</h2></div><button onClick={onBack}>Exit</button></div><div className="quiz-timer"><span style={{width:`${percent}%`}}/></div><div className="quiz-meta"><b>{seconds}s</b><span>{score.toLocaleString()} pts</span></div><article className="quiz-question"><span className="quiz-number">0{round+1}</span><h3>{question.q}</h3></article><div className="quiz-options">{question.a.map((answerText,index)=>{const state=choice===null?'':index===question.correct?'correct':index===choice?'wrong':'';return <button key={answerText} className={state} disabled={choice!==null} onClick={()=>answer(index)}><span>{String.fromCharCode(65+index)}</span>{answerText}</button>})}</div>{choice!==null&&<div className="quiz-feedback" role="status">{choice===question.correct?'Correct. Keep the energy.':choice===-1?'Time. The room moved on.':'Not this one. Next question.'}<button className="primary" onClick={next}>{round===QUESTIONS.length-1?'SEE RESULTS':'NEXT →'}</button></div>}</section>}
