import React, { useEffect, useMemo, useState } from 'react';
import { touchFeedback } from '../lib/feedback';

type Props={game:'othello'|'gomoku'|'mancala'|'word-hunt';onBack:()=>void};
const dirs=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]] as const;
const inBoard=(r:number,c:number,n:number)=>r>=0&&c>=0&&r<n&&c<n;
function Othello({onBack}:{onBack:()=>void}){const [board,setBoard]=useState(()=>{const b=Array(64).fill(0);b[27]=2;b[28]=1;b[35]=1;b[36]=2;return b});const [turn,setTurn]=useState(1);const moves=useMemo(()=>{const out:number[]=[];for(let i=0;i<64;i++){if(board[i])continue;const r=Math.floor(i/8),c=i%8;for(const [dr,dc] of dirs){let rr=r+dr,cc=c+dc,count=0;while(inBoard(rr,cc,8)&&board[rr*8+cc]===3-turn){count++;rr+=dr;cc+=dc}if(count&&inBoard(rr,cc,8)&&board[rr*8+cc]===turn){out.push(i);break}}}return out},[board,turn]);const play=(i:number)=>{if(turn!==1||!moves.includes(i))return;const next=board.slice();const r=Math.floor(i/8),c=i%8;next[i]=1;for(const [dr,dc] of dirs){const path:number[]=[];let rr=r+dr,cc=c+dc;while(inBoard(rr,cc,8)&&next[rr*8+cc]===2){path.push(rr*8+cc);rr+=dr;cc+=dc}if(path.length&&inBoard(rr,cc,8)&&next[rr*8+cc]===1)path.forEach(x=>next[x]=1)}setBoard(next);setTurn(2);touchFeedback('tap')};useEffect(()=>{if(turn!==2)return;const t=window.setTimeout(()=>{const enemyMoves=[];for(let i=0;i<64;i++){if(board[i])continue;const r=Math.floor(i/8),c=i%8;for(const [dr,dc] of dirs){let rr=r+dr,cc=c+dc,count=0;while(inBoard(rr,cc,8)&&board[rr*8+cc]===1){count++;rr+=dr;cc+=dc}if(count&&inBoard(rr,cc,8)&&board[rr*8+cc]===2){enemyMoves.push(i);break}}}if(enemyMoves.length){const i=enemyMoves[0],next=board.slice();next[i]=2;setBoard(next)}setTurn(1);touchFeedback('tap')},350);return()=>window.clearTimeout(t)},[turn,board]);return <section className="strategy-shell"><div className="room-head"><div><span className="eyebrow">OTHELLO · SOLO</span><h2>Flip the room.</h2></div><button onClick={onBack}>Exit</button></div><p className="muted">Tap a highlighted square. Bot plays the other side.</p><div className="strategy-board othello-board">{board.map((cell,i)=><button key={i} className={`${moves.includes(i)&&turn===1?'legal':''}`} onClick={()=>play(i)} aria-label={`Square ${i+1}`}>{cell===1?'●':cell===2?'○':''}</button>)}</div><p className="strategy-status">{turn===1?'Your turn':'Cruise Bot is thinking…'} · {moves.length} legal moves</p></section>}
function Gomoku({onBack}:{onBack:()=>void}){const n=10;const [board,setBoard]=useState(()=>Array(n*n).fill(0));const [turn,setTurn]=useState(1);const play=(i:number)=>{if(turn!==1||board[i])return;const next=board.slice();next[i]=1;setBoard(next);setTurn(2);touchFeedback('tap');window.setTimeout(()=>{const empty=next.findIndex(x=>!x);if(empty>=0){next[empty]=2;setBoard(next)}setTurn(1);touchFeedback('tap')},300)};return <section className="strategy-shell"><div className="room-head"><div><span className="eyebrow">GOMOKU · SOLO</span><h2>Five in a line.</h2></div><button onClick={onBack}>Exit</button></div><p className="muted">Build your line before the bot does.</p><div className="strategy-board gomoku-board">{board.map((cell,i)=><button key={i} disabled={!!cell} onClick={()=>play(i)}>{cell===1?'●':cell===2?'×':''}</button>)}</div><p className="strategy-status">{turn===1?'Your turn':'Cruise Bot is thinking…'}</p></section>}
function Mancala({onBack}:{onBack:()=>void}){const [pits,setPits]=useState(()=>Array(12).fill(4));const [turn,setTurn]=useState(0);const play=(index:number)=>{if(turn||pits[index]===0)return;const next=pits.slice();let stones=next[index];next[index]=0;let at=index;while(stones--){at=(at+1)%12;next[at]++}setPits(next);setTurn(1);touchFeedback('tap');window.setTimeout(()=>{const i=next.findIndex(x=>x>0);if(i>=0){const bot=next.slice();bot[i]=Math.max(0,bot[i]-1);setPits(bot)}setTurn(0);touchFeedback('tap')},350)};return <section className="strategy-shell"><div className="room-head"><div><span className="eyebrow">MANCALA · SOLO</span><h2>Count the moves.</h2></div><button onClick={onBack}>Exit</button></div><div className="mancala-pits">{pits.map((count,i)=><button key={i} disabled={turn!==0||!count} onClick={()=>play(i)}><b>{count}</b><small>PIT {i+1}</small></button>)}</div><p className="strategy-status">{turn===0?'Your turn':'Cruise Bot is thinking…'}</p></section>}
function WordHunt({onBack}:{onBack:()=>void}){const letters=['C','R','U','I','S','E','V','I','B','E','S','M','O','V','E','S'];const [path,setPath]=useState<number[]>([]);const [found,setFound]=useState<string[]>([]);const submit=()=>{const word=path.map(i=>letters[i]).join('');if(word.length>=3&&!found.includes(word))setFound([...found,word]);setPath([]);touchFeedback('success')};return <section className="strategy-shell"><div className="room-head"><div><span className="eyebrow">WORD HUNT · SOLO</span><h2>Find your words.</h2></div><button onClick={onBack}>Exit</button></div><p className="muted">Tap letters to build a word, then submit.</p><div className="word-hunt-board">{letters.map((letter,i)=><button key={i} className={path.includes(i)?'selected':''} onClick={()=>setPath(path.includes(i)?path:path.concat(i))}>{letter}</button>)}</div><div className="controls"><button className="primary" disabled={path.length<3} onClick={submit}>SUBMIT {path.map(i=>letters[i]).join('')}</button><button onClick={()=>setPath([])}>CLEAR</button></div><p className="strategy-status">Found: {found.join(' · ')||'none yet'}</p></section>}
export function StrategySoloGame({game,onBack}:Props){if(game==='othello')return <Othello onBack={onBack}/>;if(game==='gomoku')return <Gomoku onBack={onBack}/>;if(game==='mancala')return <Mancala onBack={onBack}/>;return <WordHunt onBack={onBack}/>}
