import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase, UNO_FUNCTION_URL } from './lib/supabase';
import './styles.css';
import { getWeeklyTheme } from './lib/theme';
import { GAMES } from './lib/cruise/catalog';
import { extractUnoState } from './lib/games/uno/response';
import type { UnoCard } from './lib/games/uno/rules';
import { isMyTurn } from './lib/games/uno/view-model';

type User={id:string;email?:string};
type Player={id:string;displayName:string;avatarUrl?:string|null;hand?:UnoCard[];handCount:number;ready:boolean};
type State={phase:'lobby'|'playing'|'finished';players:Player[];discardPile:UnoCard[];drawPileCount:number;currentPlayerIndex:number;currentColor:string;winnerId?:string;pendingUnoPlayerId?:string};
type Tab='home'|'games'|'rankings'|'community'|'merch';

async function api(action:string,data:Record<string,unknown>={}){const {data:{session}}=await supabase.auth.getSession();const r=await fetch(UNO_FUNCTION_URL,{method:'POST',headers:{Authorization:`Bearer ${session?.access_token||''}`,'content-type':'application/json'},body:JSON.stringify({action,...data})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j;}
const cardLabel=(c:UnoCard)=>c.kind==='number'?String(c.value):({skip:'⊘',reverse:'↻',draw2:'+2',wild:'WILD',wild4:'+4'} as Record<string,string>)[c.kind];
const cardColor=(c:UnoCard)=>({red:'#ef3340',yellow:'#ffd400',green:'#16a34a',blue:'#2563eb',wild:'#151515'} as Record<string,string>)[c.color];

function ThemeBadge({theme}:{theme:ReturnType<typeof getWeeklyTheme>}){return <span className="theme-badge">{theme.icon} {theme.shortLabel}</span>}
function Header({theme,onTab,tab,onSignOut}:{theme:ReturnType<typeof getWeeklyTheme>;onTab:(t:Tab)=>void;tab:Tab;onSignOut:()=>void}){return <header className="app-header"><button className="brand" onClick={()=>onTab('home')}>BIG CRUISE<span>〽️</span></button><div className="header-right"><ThemeBadge theme={theme}/><button className="ghost" onClick={onSignOut}>Exit</button></div></header>}

function Home({theme,onTab}:{theme:ReturnType<typeof getWeeklyTheme>;onTab:(t:Tab)=>void}){const featured=GAMES.filter(g=>theme.featuredGames.includes(g.id));return <main className="page"><section className="today"><div className="eyebrow">TODAY'S CRUISE</div><div className="theme-icon">{theme.icon}</div><h1>{theme.displayName}</h1><p>{theme.description}</p><div className="challenge"><b>🔥 TODAY'S CHALLENGE</b><span>{theme.challenge}</span></div><button className="primary big" onClick={()=>onTab('games')}>PLAY TODAY'S CRUISE →</button></section><section><div className="section-head"><div><span className="eyebrow">FEATURED</span><h2>Games for today</h2></div><button className="link" onClick={()=>onTab('games')}>See all</button></div><div className="game-grid">{featured.map(g=><GameCard key={g.id} game={g} onPlay={()=>onTab('games')}/>)}</div></section><section className="promo-row"><div><span className="eyebrow">7 DAYS OF CRUISE</span><h2>A new reason to pull up every day.</h2><p>Games, challenges and community energy change with the day.</p></div><button onClick={()=>onTab('rankings')}>View rankings</button></section></main>}
function GameCard({game,onPlay}:{game:(typeof GAMES)[number];onPlay:()=>void}){return <button className={`game-card ${game.status}`} onClick={onPlay}><span className="game-art" style={{'--game-accent':game.accent} as React.CSSProperties}>{game.icon}</span><span className="game-meta"><b>{game.name}</b><small>{game.status==='playable'?'PLAY NOW':'COMING SOON'}</small></span><span className="game-arrow">→</span></button>}

function Games({theme,user}:{theme:ReturnType<typeof getWeeklyTheme>;user:User}){const [selected,setSelected]=useState('uno');const [state,setState]=useState<State|null>(null);const [roomId,setRoomId]=useState('');const [code,setCode]=useState('');const [joinCode,setJoinCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const game=GAMES.find(g=>g.id===selected)!;
 const run=async(action:string,data:Record<string,unknown>={})=>{try{setBusy(true);setError('');const j=await api(action,data);const s=extractUnoState(j);if(s)setState(s as State);if(j.roomId)setRoomId(j.roomId);if(j.code)setCode(j.code);if(action==='join'&&j.roomId&&!s){const q=await api('state',{roomId:j.roomId});const ss=extractUnoState(q);if(ss)setState(ss as State)}}catch(e){setError(e instanceof Error?e.message:'Something went wrong')}finally{setBusy(false)}};
 useEffect(()=>{if(!roomId)return;const id=setInterval(()=>void run('state',{roomId}),1800);return()=>clearInterval(id)},[roomId]);
 if(selected!=='uno')return <main className="page"><div className="section-head"><div><span className="eyebrow">🎮 BIG CRUISE ARCADE</span><h1>{game.icon} {game.name}</h1></div><button onClick={()=>setSelected('uno')}>Back to UNO</button></div><section className="coming"><div className="coming-icon">{game.icon}</div><h2>{game.name} is joining the Cruise.</h2><p>The game slot and weekly-theme integration are ready. Its licensed game engine will plug into this same BIG CRUISE identity, room and points system.</p><button className="primary" onClick={()=>setSelected('uno')}>Play UNO instead</button></section></main>;
 if(!state)return <main className="page"><div className="section-head"><div><span className="eyebrow">🎮 BIG CRUISE ARCADE</span><h1>Choose your game.</h1><p className="muted">{theme.icon} {theme.displayName} · today's featured games are highlighted.</p></div></div><div className="game-grid all">{GAMES.map(g=><GameCard key={g.id} game={g} onPlay={()=>setSelected(g.id)}/>)}</div><section className="uno-entry"><div><span className="eyebrow">UNO ONLINE</span><h2>Pull up with your people.</h2><p>One BIG CRUISE login. Real rooms. Real players.</p></div><div className="actions"><button className="primary" onClick={()=>run('create')} disabled={busy}>Create room</button><div className="join"><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="ROOM CODE" maxLength={6}/><button onClick={()=>run('join',{code:joinCode})} disabled={busy||joinCode.length<4}>Join</button></div></div>{error&&<p className="error">{error}</p>}</section></main>;
 const me=state.players.find(p=>p.id===user.id);const current=state.players[state.currentPlayerIndex];const myTurn=isMyTurn(state,user.id);const top=state.discardPile.at(-1);const hand=me?.hand||[];const play=async(c:UnoCard)=>{if(c.color==='wild'){const chosen=window.prompt('Choose color: red, yellow, green or blue');if(chosen&&['red','yellow','green','blue'].includes(chosen))await run('play',{roomId,cardId:c.id,chosenColor:chosen});return}await run('play',{roomId,cardId:c.id})};
 return <main className="page"><div className="room-head"><div><span className="eyebrow">ROOM {code}</span><h1>UNO <span className="yellow">〽️</span></h1><ThemeBadge theme={theme}/></div><button onClick={()=>{setState(null);setRoomId('');setCode('')}}>Leave room</button></div><section className="uno-table"><div className="seats">{state.players.map((p,i)=><div className={`seat ${i===state.currentPlayerIndex&&state.phase==='playing'?'active':''}`} key={p.id}><span className="avatar">{p.displayName.slice(0,1).toUpperCase()}</span><div><b>{p.displayName}</b><small>{p.handCount} cards {i===state.currentPlayerIndex&&state.phase==='playing'?'• TURN':''}</small></div></div>)}</div><div className="table-center"><button className="draw-pile" disabled={!myTurn||busy} onClick={()=>run('draw',{roomId})}>{state.drawPileCount}<small>DRAW</small></button>{top&&<div className="big-card" style={{background:cardColor(top)}}>{cardLabel(top)}</div>}<div className="status">{state.phase==='lobby'?'WAITING FOR PLAYERS':state.phase==='finished'?`${state.players.find(p=>p.id===state.winnerId)?.displayName||'Someone'} wins!`:myTurn?'YOUR TURN':`${current?.displayName||'Opponent'}'s turn`}<small>{state.phase==='lobby'?`${state.players.length}/4 PLAYERS`:`COLOR: ${state.currentColor.toUpperCase()}`}</small></div></div><div className="hand">{hand.map(c=><button key={c.id} className="uno-card" style={{background:cardColor(c)}} disabled={!myTurn||busy} onClick={()=>void play(c)}>{cardLabel(c)}</button>)}</div><div className="controls">{state.pendingUnoPlayerId===user.id&&<button className="primary" onClick={()=>run('call_uno',{roomId})}>UNO! 🚨</button>}{state.phase==='lobby'&&<button className="primary" onClick={()=>run('ready',{roomId,ready:true})}>Ready</button>}{state.phase==='lobby'&&state.players.length>=2&&state.players.every(p=>p.ready)&&<button onClick={()=>run('start',{roomId})}>Start game</button>}{state.phase==='finished'&&<button className="primary" onClick={()=>run('rematch',{roomId})}>Rematch</button>}</div>{error&&<p className="error">{error}</p>}</section></main>}

function Merch(){return <main className="page"><section className="merch-hero"><span className="eyebrow">🛍️ BIG CRUISE MERCH</span><h1>Wear the Cruise.</h1><p>A real in-app storefront for BIG CRUISE drops. Product catalogue, variants, cart and checkout plug into this same PWA.</p></section><div className="product-grid"><Product name="BIG CRUISE〽️ Core Tee" price="₦25,000"/><Product name="DOMINION STATE Hoodie" price="₦45,000"/><Product name="BIG CRUISE〽️ Cap" price="₦18,000"/></div></main>}
function Product({name,price}:{name:string;price:string}){return <article className="product"><div className="product-art">〽️</div><div><b>{name}</b><span>{price}</span></div><button className="primary" onClick={()=>alert('Product catalogue/checkout is being connected to live inventory.')}>View product</button></article>}
function Simple({title,body}:{title:string;body:string}){return <main className="page"><section className="empty-page"><span className="eyebrow">BIG CRUISE〽️</span><h1>{title}</h1><p>{body}</p></section></main>}

function App(){const theme=useMemo(()=>getWeeklyTheme(new Date()),[]);const [user,setUser]=useState<User|null>(null);const [tab,setTab]=useState<Tab>('home');useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)setUser({id:data.session.user.id,email:data.session.user.email})});const s=supabase.auth.onAuthStateChange((_e,session)=>setUser(session?{id:session.user.id,email:session.user.email}:null));return()=>s.data.subscription.unsubscribe()},[]);if(!user)return <main className="auth"><div className="logo">BIG CRUISE<span>〽️</span></div><ThemeBadge theme={theme}/><p className="eyebrow">ONE LOGIN. EVERY CRUISE.</p><Login onUser={setUser}/></main>;return <div className="app"><Header theme={theme} onTab={setTab} tab={tab} onSignOut={()=>void supabase.auth.signOut()}/>{tab==='home'&&<Home theme={theme} onTab={setTab}/>} {tab==='games'&&<Games theme={theme} user={user}/>} {tab==='merch'&&<Merch/>} {tab==='rankings'&&<Simple title="Cruise Rankings" body="Daily, weekly and all-time rankings will aggregate results from every in-app game and weekly challenge."/>} {tab==='community'&&<Simple title="The Cruise" body="Your community layer is where game results, challenges, profiles and weekly culture come back together."/>}<nav className="bottom-nav">{([['home','🏠','Cruise'],['games','🎮','Games'],['rankings','🏆','Rankings'],['community','👥','Community'],['merch','🛍️','Merch']] as const).map(([id,icon,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}><span>{icon}</span><small>{label}</small></button>)}</nav></div>}
function Login({onUser}:{onUser:(u:User)=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [signup,setSignup]=useState(false);const [error,setError]=useState('');return <form className="auth-form" onSubmit={async e=>{e.preventDefault();const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);else if(r.data.user)onUser({id:r.data.user.id,email:r.data.user.email})}}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary" type="submit">{signup?'Create your seat':'Walk in'}</button>{error&&<p className="error">{error}</p>}<button type="button" className="link" onClick={()=>setSignup(!signup)}>{signup?'Already cruising? Log in':'Need an account? Create one'}</button></form>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
